### ISSUE TITLE
ezSystem missing on OSX and Linux

### ISSUE THREAD

**Issue by Manuzor** [ezEngine/ezEngine#10]
On OSX and Linux, I was unable to generate a project for and thus build `ezSystem`. Quoting `Code/Engine/System/CMakeLists.txt(73)`:
> Someone else finish the MacOS and Linux setup...

Is it possible that you already fixed this in your SVN repo?

**Comment by jankrassnigg** [comment]
Nope, so far no one tried to do anything on Mac and Linux that required a window, so no one has found it important to finish this.

Someone would need to provide libraries:
Code\ThirdParty\SFML\libs\LinuxGCC
Code\ThirdParty\SFML\libs\MacClang

Those folders are empty at the moment. Also the build file for ezSystem would need to be set up.

Additionally the SFML port has not been tested in a while. On Windows we create windows ourselves, we actually mostly need SFML for Mac and Linux ...
You could use SFML on Windows as well, if you just want to try it out, by setting EZ_SUPPORTS_SFML to EZ_ON. But SFML is a bit simplistic regarding input, so on Windows it makes sense to not use SFML.

**Comment by Manuzor** [comment]
So, the code for window creation is already there for OSX and Linux but the build-system is not set up yet, right? I assume ezSystem is completely untested on OSX and Linux then?

**Comment by jankrassnigg** [comment]
Yep.

Btw. we used SFML 2.1, the latest version is 2.2, not sure which changes there have been and whether it makes sense to upgrade.
