### ISSUE TITLE
[BUG] Global Blackboards retrain state across editor lifetime

### ISSUE THREAD

**Issue by jankrassnigg** [ezEngine/ezEngine#1061]
Global blackboards are never cleared, thus state easily leaks between simulation runs.

Maybe we should clear them after one run.

**Comment by C-Core** [comment]
Well global blackboards can track state across the world lifetime so the behavior is "correct" for the runtime. For the editor use case we can probably clear them when the simulation is stopped, but that would be editor specific code.

**Comment by jankrassnigg** [comment]
I've been thinking a bit more about my use case and came to the conclusion that what I wanted is not a fully global blackboard, but rather one that is scene-specific. Ie globally accessible, but with a blank state every time I load a new level.

However, adding a new type with special behavior would make things more complicated, and I think it is relatively easy to change the current infrastructure to make it all a bit more useful. Actually all we need is to modify the blackboard component a little.

I would propose to add a mode to the component:

1) Local
2) Global - Only Add Non-existing Keys/Values
3) Global - Overwrite all values
4) Global - Clear all Keys and Set Values

In any of the global modes, it would retrieve a global blackboard and only modify it with the values from its BB template.
The component may either fully reset the BB, or just make sure that the values exist.

This way one can simply add a BB component to a scene to make sure that a global BB is set up and in the proper default state, such that other code does not need to worry about default values anymore.

Also with modes 3 and 4, you can guarantee that a BB gets reset every time you load a scene. Or at least those values of interest (The ones in the template). Ie you could have multiple BB components add values to the same BB, using different templates.

But now it is the developer's choice. If they want to retain state across runs or across documents, this is still possible (might actually be quite useful for testing), and there is no difference between editor and runtime behavior.
