### ISSUE TITLE
[BUG] Closing Editor Document Windows Does Not Properly Serialize The Last Closed Window.

### ISSUE THREAD

**Issue by TheophilusE** [ezEngine/ezEngine#1109]
**Bug description:**
The last closed window is not properly serialized, which causes it to open undocked on reopening project.

**How to Reproduce:**
1. Create or open an Editor project.
2. Open an asset in a new tab (just one is needed).
3. Close the opened tab.
4. Close and reopen Editor.

**Screenshots:**
If applicable, add screenshots to help explain the problem.

**Dev-branch commit hash:**
Dev branch commit hash c38b57a2ba3939d4c77c94d89b1abe9510becb2e

**Comment by Sanakan8472** [comment]
Fixed in #1110.
