### ISSUE TITLE
[BUG] Adding / Removing pins in render pipeline assets is broken

### ISSUE THREAD

**Issue by jankrassnigg** [ezEngine/ezEngine#1134]
Changing the render pipeline graph connections crashes.

It works in visual scripts and visual shaders.

**Comment by jankrassnigg** [comment]
After bisecting the commit history, it seems this change broke it:

5 Sep 2023 20:25:43 +02:00
Fix Vulkan MSAA Issue + Linux fixes (#1017)
c46e3b4b2cd46798e4abb4938fbca281c054b039

**Comment by Ingrater** [comment]
I'll take a look
