### ISSUE TITLE
[FEATURE] Level Of Detail System

### ISSUE THREAD

**Issue by JailbreakPapa** [ezEngine/ezEngine#1151]
**Describe the solution you'd like:**
When a user imports/creates a model within the engine, the Asset transform system should generate LOD's (0-5) for that mesh. it should be also configurable to allow the user to also import their own LOD Levels (manually authored LOD mesh's, that the user can just provide a path to in the editor). 

At Runtime, the engine query's each mesh that is Dynamic/Static (or both) and tests how far they are from the camera (rendered view). we apply the LOD Level based on the camera frustum, Near/Far plane, or varying levels of distance.

There are many other ways for this to be calculated, like doing it within screen-space, which fits more dynamic scenes better.

For how mesh LOD's can be "generated" mesh-optimizer can be a good, nice MIT Licensed tool for helping generate them.[https://github.com/zeux/meshoptimizer](Meshoptimizer)

**Additional context:**
A LOD System is Hard to implement within a engine like this, but I feel like it should still be tackled. 

The solutions I'm describing here are very "high level" and is just a basic implementation of a LOD system. feel free to give feedback.

**Comment by jankrassnigg** [comment]
We now have:
* ezLodComponent for switching between entire objects as LODs
* ezLodMeshComponent for switching only between multiple meshes
* Automatic mesh simplification on the Mesh Asset

Future work:
* Automatic LOD generation for animated meshes
* Component for switching animated LOD meshes.

**Comment by PlasmaDev5** [comment]
Would potentially be good if the setup of this could be auto setup in some form.
When your at the scale where LOD would make a huge difference it would take a sizable amount of time to create all the lod meshes and setup the components.
