### ISSUE TITLE
Website footer needs to mention cookie policy

### ISSUE THREAD

**Issue by jankrassnigg** [ezEngine/ezEngine#1162]
The website stores a cookie for the color theme, this needs to be mentioned somewhere, otherwise it would violate European law.

@jayrulez can you look into this?

**Comment by jayrulez** [comment]
Yes, I've had this as a TODO for the past few days now. I'll add it.

**Comment by jayrulez** [comment]
WIP here: https://github.com/ezEngine/docs-src/compare/main...privacy-policy

If there is some specific text you'd like, then let me know. Otherwise, I could just come up with something.

**Comment by jayrulez** [comment]
Done: https://ezengine.net/privacy-policy.html

Feel free to make changes to the wording on the policy page.

**Comment by jankrassnigg** [comment]
Awesome, thanks a lot for the help! The updated website looks even better :)
