### ISSUE TITLE
[FEATURE] Auto Import All Animation Clips

### ISSUE THREAD

**Issue by PlasmaDev5** [ezEngine/ezEngine#1163]
When importing a file that contains multiple animation clips i feel it would make sense for the editor to split each clip into its own animation file. The engine seams aware of the contents as it provides a list of available clips that can not be interacted with. Currently having to create a new an Animation Clip feels very tedious and time consuming.

![image](https://github.com/ezEngine/ezEngine/assets/3044415/df7dd15e-e218-44e3-8c3d-b0faba9418e5)

**Comment by jankrassnigg** [comment]
Yes, I wanted to add this feature for a long time already, never got around to it. But now all the other infrastructure is in place that this absolutely makes sense.

Basically the asset importer for animation files needs to open the files itself already, get the list of available clips and then create one asset file for each and automatically set the animation clip string accordingly. Not too complicated.
