### ISSUE TITLE
Allow ResourceHandle properties without string getter/setter

### ISSUE THREAD

**Issue by jankrassnigg** [ezEngine/ezEngine#1164]
Make it possible to expose a resource handle as a property to the editor (with the proper asset browser property automatically) without the need for string accessor functions.

**Comment by C-Core** [comment]
Note that the string properties are also exposed to script which allows scripts to get and set resource properties easily. Scripts don't know anything about resource handles so if we get rid of the string accessor functions we have to think about how this can be exposed in scripts.

**Comment by jankrassnigg** [comment]
I haven't had time to think about this. Though maybe as a start we could just add a macro that does the boiler plate for you? Ie nothing would change, it's just more convenient.
