### ISSUE TITLE
[FEATURE] Asset Browser improvements

### ISSUE THREAD

**Issue by PlasmaDev5** [ezEngine/ezEngine#1194]
Writing up a few minor asset browser improvements to make it behave closer to system explorers and other engines.

- Drag and drop import
- Drag and drop moving of files
- Rename in context menu (right click)
- Duplicate files
- Back button to move up a directory (map to mouse back button if available)
- When filtering by asset only show folders containing that asset type

**Comment by jankrassnigg** [comment]
Most of this has been implemented.
