### ISSUE TITLE
ezPreprocessor/ezTokenizer fails to parse Engine\Foundation\Basics.h

### ISSUE THREAD

**Issue by Wumpf** [ezEngine/ezEngine#12]
It seems ezPreprocessor has trouble with its own files. I used an adequate FileLocator function and the following custom defines: `"WIN32", "_DEBUG", "_WINDOWS"`
The ezTokenizer fails for me in ezTokenizer::HandleString2 with "String not closed at end of file." while tokenizing `Platform_win.h`
At this point in time the m_szTokenStart dubiously points at this string part:
```
"
#endif

#undef EZ_PLATFORM_LITTLE_ENDIAN
#define EZ_PLATFORM_LITTLE_ENDIAN EZ_ON
```
Later on the preprocessor runs into the error "Undefined platform!" in Basics.h ln18, apparently because it thinks the `#else` path belongs to the defines in `Platform_win.h`

The exact origin and reason of this error is not yet clear to me though.

**Comment by jankrassnigg** [comment]
I'll have a look at it.

**Comment by Wumpf** [comment]
Thank you! :)
I just uploaded the project [to github](https://github.com/Wumpf/IncludeViewer) where I stumbled over that error, just in case you cannot reproduce it. Code in question is [here](https://github.com/Wumpf/IncludeViewer/blob/master/IncludeParser/IncludeParser.cpp) 

Oh and since I still have access to the ez SVN repo it might be necessary to clarify that I use the Github version (simply because I wanted to have ez as a submodule).

**Comment by jankrassnigg** [comment]
It seems to be a problem with using #error and not putting the text into proper quotes. I have distilled it down to this:

#error Before bad quote ' After bad quote

This unit test produces the following for me:

Processing failed
Log: 'String not closed at end of file.'
Preprocessor/Bug1.txt: Line 1 [2]: Error: #error 'Before bad quote ' After bad quote'

Wrap it into proper "quotes" and it works fine. I check out how to fix it.

**Comment by jankrassnigg** [comment]
If you want to try it out, Platform_win.h has an error in line 3:
#error "This header should only be included on windows platforms

Just add a quote and see whether that fixes it for you already (these seem to be two bugs, one in the preprocessor, one in the actual header).

**Comment by jankrassnigg** [comment]
I just committed a fix (and some more unit tests) for the string handling into the SVN repository. If you want it in GitHub, please test whether the change can be applied to that state and commit it.

**Comment by Wumpf** [comment]
Thank you so much! Your fix did the trick. :-)

... although I have now errors during parsing headers deep within the standard library. I need to investigate if this is actually a fault in the preprocessor or (as I suspect) built-in macro I haven't defined and/or things msvc treats different.
```
Error: File 'C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include/sal.h', Line 2743 (9): Redefinition of macro '__inout_ecount_z_opt'
Error: File 'C:/Program Files (x86)/Windows Kits/8.1/Include/shared/sal.h', Line 146 (9): Redefinition of macro '__ATTR_SAL'
```

**Comment by jankrassnigg** [comment]
If this is supposed to work, it would be easy to add a flag to tell the preprocessor to silently ignore redefinitions. Or one could even add a callback that allows to do custom filtering on such redefinitions.

This is nothing serious, it just complains, because redefinitions violate the specification, but they actually don't break anything.
