### ISSUE TITLE
[FEATURE] Enable EditorEngineProcess callstack printing & make it clickable

### ISSUE THREAD

**Issue by RiederAlex** [ezEngine/ezEngine#1210]
It would be very useful to always enable callstack printing for the EditorEngineProcess and be able to jump directly to the source of the problem going from ezEditor -> Code IDE by clicking on the various entries in the callstack.

I have a prototype with hardcoded paths working, which looks like this:

https://github.com/ezEngine/ezEngine/assets/14026803/98037624-fb54-4828-a616-ffdcc04144cc

Here is my proposal how I would like to implement this properly:
1. Always enable the CrashHandler in `ezEngineProcessGameApplication::AfterCoreSystemsStartup`
2. Add static global callbacks for double-clicking on LogMessages in `ezQtLogWidget`
    This is then something that can be used by each editor plugin to provide specific actions when double clicking on an log entry
3. Implement callstack-logmessage parsing somwehre in the Editor, using this new callback
4. Allow the user to configure a "Open in IDE" action via Application: General settings
    This would be a freeform text field which the user can configure to point towards their IDE, like:
      `..../clion64.exe --line {line} {file}`
    where {line} and {file} would be dynamically replaced with the information parsed from step 3).

Potentially problematic points I've identified so far/I am unsure about:

5. Log messages have no context, which means that log message parsing is plain string parsing. Potentially it would be nice to have some form of metadata attached to log messages.
  This is not scope of this feature, but just something to keep in mind. To ensure this plaintext parsing behaves well in this case, I'll add unit tests.
6. Currently this action is done by double clicking on a log message. However in the future it could happen that multiple plugins parse a log message and want to perform actions. I'm thinking of changing the design to be right click -> open context menu and have a list of plausible actions.
7. The callstack-logmessage parsing has to be implemented for each platform and I'm not sure how the callstack looks in Linux/if its even possible to open a file without additional meta information. Right now this would be windows only.

Implementing this as a first step would allow a couple of nice things in the future potentially, like jumping to a component definition (as we now have "open this file/line in IDE" action) or if its decided to add more metadata to the log messages, be able to jump directly to the gameobject/component/system which logged certain messages.

If this sounds like the right approach I would like to take over implementation on this.

**Comment by jankrassnigg** [comment]
This is a really great suggestion. I'd be happy for you to implement it in the proposed way.

A couple of random thoughts.

1. There was an idea at some point that we should support multi-line log messages. No one ever had time to look into this, though. Not sure whether this would be useful here, actually it would probably make it harder for people to double click on a specific callstack entry.
2. Double-click sounds fine. It's not that discoverable, so an additional context menu would be great, but isn't necessary for the first version.
3. Note that the log system supports "tags", ie if a message starts with "[bla]Hello" then everything in the square brackets is passed along as an invisible tag. It's very rudimentary, but it could be sufficient to determine which handler to call. This would also allow to show a context menu entry for the action that would be taken.
4. I've seen more sophisticated systems of passing along meta data, but so far none have convinced me, either they were too bloated and inefficient or quickly overused by people in completely unnecessary ways. Usually both.
5. We currently specifically output the callstack such that MSVC can deal with it nicely. I'd guess that most other IDEs support the same syntax, if not, not important to us right now.
6. There is already a preference for you preferred compiler and IDE for the C++ project stuff. Have a look whether that is already sufficient for you.
7. I like the idea to be able to later also open up the code for a component in the IDE. Not sure how that could be achieved (I guess this needs relative paths and a base path to your code).

**Comment by RiederAlex** [comment]
Great, then I'll go ahead and start implementing it properly :)

To respond to your points:

3) I'll try to check if the tag system makes it easier, as to maybe only have certain context actions for certain tags.

4) I'm was honestly thinking of something very rudimentary like "__file__ __line__" to know where the source of certain messages is from, so they can be traced from the ezEditor -> IDE. But this sounds like a future task.

6) Oh I've seen this, maybe I can re-purpose it. Potentially I'll have to add Clion as supported IDE.

7) In the first iteration it would also only work for locally build editors,
as there we know where the file is w/o having to point it towards a base source-package. Again, future task :)
