### ISSUE TITLE
[BUG] ezTypedComponentHandle isn't typesafe

### ISSUE THREAD

**Issue by x0r04rg** [ezEngine/ezEngine#1259]
Consider this code:
```cpp
ezTypedComponentHandle<ezMeshComponent> hMeshComp;

ezLocalBlackboardComponent* pBlackboardComp = nullptr;
if (GetWorld()->TryGetComponent(hMeshComp, pBlackboardComp))
{
  // ...
}
```

The purpose of ezTypedComponentHandle is to catch bugs like these at compile time. But this code compiles successfully because ezTypedComponentHandle decays into ezComponentHandle and the untyped overload of TryGetComponent is called.

**Comment by jankrassnigg** [comment]
If someone has suggestions how to fix it, I'm all ears.

**Comment by x0r04rg** [comment]
I think I'm onto something - will make a PR later today
