### ISSUE TITLE
[BUG] when qt is disabled, it gets downloaded during build

### ISSUE THREAD

**Issue by brightening-eyes** [ezEngine/ezEngine#1281]
**Bug description:**
I am adding ezengine as a submodule to a little project (just for my learning), and I want to disable qt support
**How to Reproduce:**
here is the CMakeLists.txt that I am using:
```
cmake_minimum_required(VERSION 3.16)
set(EZ_3RDPARTY_ZSTD_SUPPORT ON)
set(EZ_3RDPARTY_ZLIB_SUPPORT ON)
set(EZ_3RDPARTY_TRACY_SUPPORT ON)
set(EZ_3RDPARTY_RECAST_SUPPORT ON)
set(EZ_3RDPARTY_OZZ_SUPPORT ON)
set(EZ_3RDPARTY_LUA_SUPPORT OFF)
set(EZ_3RDPARTY_KRAUT_SUPPORT ON)
set(EZ_3RDPARTY_JOLT_SUPPORT ON)
set(EZ_3RDPARTY_IMGUI_SUPPORT ON)
set(EZ_3RDPARTY_GLFW_SUPPORT ON)
set(EZ_BUILD_FMOD OFF)
set(EZ_3RDPARTY_ENET_SUPPORT ON)
set(EZ_3RDPARTY_DUKTAPE_SUPPORT ON)
set(EZ_3RDPARTY_ADS_SUPPORT OFF)
set(EZ_BUILD_OPENVR OFF)
set(EZ_ENABLE_QT_SUPPORT OFF)
set(EZ_BUILD_FMOD OFF)
set(EZ_BUILD_RMLUI OFF)
set(EZ_ENABLE_QT_SUPPORT OFF)
set(EZ_BUILD_UNITTESTS OFF)
include("ezEngine/Code/BuildSystem/CMake/ezUtils.cmake")
ez_detect_languages()
project("loc" LANGUAGES ${EZ_LANGUAGES})
add_subdirectory(ezengine)
add_subdirectory(proj)
```
proj is where I copied HelloWorld app for ezengine
here is the command that I am using to build:
```
cmake .. -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
```
here is HelloWorldApp.cpp which I've removed vs logging:
```
#include <Foundation/Application/Application.h>
#include <Foundation/Logging/ConsoleWriter.h>

class ezHelloWorldApp : public ezApplication
{
public:
    ezHelloWorldApp() : ezApplication("ezHelloWorld")
    {
    }

    virtual void AfterCoreSystemsStartup() override
    {
        ezGlobalLog::AddLogWriter(ezLogWriter::Console::LogMessageHandler);
    }

    virtual void BeforeCoreSystemsShutdown() override
    {
        // prevent further output during shutdown
        ezGlobalLog::RemoveLogWriter(ezLogWriter::Console::LogMessageHandler);
    }

    ApplicationExecution Run() override
    {
        ezLog::Info("Hello ezWorld!");
        return ezApplication::Quit;
    }
};

EZ_CONSOLEAPP_ENTRY_POINT(ezHelloWorldApp);

```
**Screenshots:**
n/a

**Dev-branch commit hash:**
6fccd651fb1dab9a451344692a3e24821faf3f7b

**Comment by brightening-eyes** [comment]
the thing is no matter how I do it, (even when I download qt and place it in QT_DIR), it will redownload that again.

**Comment by jankrassnigg** [comment]
This is probably just a minor bug in the CMake files, that don't respect the flag that Qt won't be used.

In the file CMake\CMakeUtils\ezUtilsQt.cmake the function `ez_prepare_find_qt` will download the Qt binaries. It doesn't check `EZ_ENABLE_QT_SUPPORT`, but not sure whether it should do that internally, or whether the entire function shouldn't even be called. Several other functions in that file are guarded with `ez_requires_qt()`.

I don't really have the time to investigate this, and since I always want to build the tools, this is a very low-priority issue. But if it bothers you, you could have a look at that file and see if you can fix it.

**Comment by brightening-eyes** [comment]
I will do that (as I do not need qt. and as my home connection is somehow limited, I cannot always download it).

**Comment by brightening-eyes** [comment]
another thing that I've seen in the cmake was directX sdk.
if someone really does not need it (maybe one wants vulkan instead), then it can be skipped. maybe with EZ_ENABLE_DX_SUPPORT as well

**Comment by jankrassnigg** [comment]
There is an experimental Vulkan port in progress. But CMake only sets up the DX linking stuff, it doesn't download anything.
