### ISSUE TITLE
[FEATURE] inverse kinematic support

### ISSUE THREAD

**Issue by brightening-eyes** [ezEngine/ezEngine#1282]
**Is your feature request related to a problem? Please describe:**
having inverse kinematic support (the motion when an arm picks up something, opens/closes a dor like the door for a car), or when a character walks, the position of his/her foot can be determined with it. it will help to have a better simulation of this stuff.

**Describe the solution you'd like:**
I suppose it need to be a world module like jolt etc and a system for startup stuff with inverse kinematic component. (I think I am wrong at some points).

**Additional context:**
[here](https://github.com/TheComet/ik) is a library in pure C that implements this. maybe we can use it as it seems accurate.

**Comment by PlasmaDev5** [comment]
The engine already supports IK. you can see it added in the following commit https://github.com/ezEngine/ezEngine/commit/6709ad6f86234706da83073215a0c0c305be361e

**Comment by brightening-eyes** [comment]
@PlasmaDev5 
thanks for pointing it out. I didn't see it.
so, this can be closed.
also I suppose it will be there in the next release.
