### ISSUE TITLE
jolt: different options based on the architecture and preference in build

### ISSUE THREAD

**Issue by brightening-eyes** [ezEngine/ezEngine#1289]
hello,
I opened this issue in order to represent jolt definitions better in ezengine's cmake scripts
* first, no matter how you build ezengine (weather static or dynamic), jolt gets built as a dynamic library. like enet, lua etc it should be set as the preference for each user.
* second, jolt.cmake has many useful defines (like double precision, different instruction sets) etc which can be tuned in the cmake script to have better performance. maybe modifying and then including jolt.cmake directly should make sense? because it handles stuff like fma, floating point exceptions, fastmath etc.
* jolt.h should be the precompiled header I suppose, as the jolt.cmake script sets it.
* I also suppose in cmake, things like USE_AVX, USE_AVX2 etc need to be have EZ_ prefix? maybe its not needed at all and I am biased a little.
thanks

**Comment by jankrassnigg** [comment]
Regarding the first point, all you probably need to change is this:

```cpp
ez_create_target(SHARED_LIBRARY ${PROJECT_NAME} NO_EZ_PREFIX)
```

to this:

```cpp
ez_create_target(LIBRARY ${PROJECT_NAME} NO_EZ_PREFIX)
```

Then it automatically uses static or dynamic linking.

I don't think using Jolt's cmake file would be a good idea, it would not integrate well into the EZ build system. I also think that this is more of an academic discussion. You don't want to build EZ with N different ways of building Jolt. At least I don't want that, that's just making maintenance a lot harder. I prefer to have a good default configuration. If we need different Jolt settings, then we can control that, but giving users all those options has no clear benefit in my opinion.

For example double precision only makes sense for large worlds. EZ doesn't use double precision internally, so it couldn't give Jolt the values, so there is no point in enabling that now.
All of the instruction set tuning you can do in a custom branch, if you really run into an issue and are working on a specific platform. Nobody is stopping you from adjusting that. But I currently don't see that anyone has a real world issue that needs fixing.

>jolt.h should be the precompiled header I suppose, 

Feel free to open a PR for that. Jolt compiles for me in 2 seconds or so, so I don't see the need, but sure, if you feel like it, fix it.

**Comment by brightening-eyes** [comment]
hello,
the compilation time for me is fast enough, I proposed jolt.h to be precompiled header to make it faster a little again.
I will also open a pr for building jolt like other parts in ezengine and the precompiled thing.
