### ISSUE TITLE
[BUG] static ezengine cant load renderer

### ISSUE THREAD

**Issue by brightening-eyes** [ezEngine/ezEngine#1294]
**Bug description:**
I've built a simple game state class derived from ezGameState in order to start developing my own game. but when executed, this will be the resulting assert:
```
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Assertion Failed!

Program: D:\eztestgame\Output\Bin\WinVs2022Debug64\tst.exe
File: D:\eztestgame\ezengine\Code\Engine\RendererFoundation\Device\Implementation\DeviceFactory.cpp
Line: 22

Expression: 'ezPlugin::LoadPlugin(sPluginName).Succeeded()'
Function: GetCreatorFuncInfo
Message: Renderer plugin 'ezRendererDX11' not found

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)

---------------------------
Abort   Retry   Ignore   
---------------------------
```

**How to Reproduce:**
I've used this cmakeLists to build my app:
```
ez_cmake_init()
ez_requires_renderer()

get_filename_component(PROJECT_NAME ${CMAKE_CURRENT_SOURCE_DIR} NAME_WE)
ez_create_target(APPLICATION ${PROJECT_NAME})
ez_make_winmain_executable(${PROJECT_NAME})
ez_add_renderers(${PROJECT_NAME})
# link against ezEngine Foundation and GameEngine
target_link_libraries(${PROJECT_NAME} PUBLIC Foundation GameEngine RendererDX11 XBoxControllerPlugin)
set_property(TARGET ${PROJECT_NAME} PROPERTY CXX_STANDARD 20)
```
maybe its from ez plugin loading?

**Screenshots:**
n/a

**Dev-branch commit hash:**
using the latest from dev branch

**Comment by Sanakan8472** [comment]
What platform is this? For static linking to work, the extern C functions in each plugin called `ezReferenceFunction_*` need to be imported into your exe to prevent the plugin from being stripped away by the linker.
On android, we fix this by providing the following flag to the linker: `--undefined-glob=*ezReferenceFunction*`. This is only supported by clang I think. If you are on another compiler / platform, you will need to find another way of preserving the linker reference.
Alternatively, you can in some cpp in your exe do the following:
```
extern void ezReferenceFunction_RendererDX11(bool bReturn = true);
...
# Call this somewhere:
ezReferenceFunction_RendererDX11(true);
```

**Comment by brightening-eyes** [comment]
I am on windows with msvc 19.35 compiler.
maybe in the cpp file of my own, I need to call this.
in the constructor of my class I suppose.

**Comment by Sanakan8472** [comment]
Yes we don't have a solution for Windows right now for static linking to preserve the plugins. You can look into msvc static linker flags, or you can try the code above. Note that the function declaration above it probably wrong, it needs to be extern c.

**Comment by jankrassnigg** [comment]
* Did you check whether the RendererDX11 library is built, at all?
* Is it really a static library? The CMake doesn't say anything about it, so it may still be built as a DLL and maybe it's just in a different path than where your app searches for it.
* Why do you do things differently than intended, in the first place? There are multiple ways that you can write your application, the easiest one would be to just copy the ezPlayer entirely and turn it into your own game application. Also you SHOULD put your game into a plugin, so that you can use the editor.

See the [Monser Attack](https://github.com/ezEngine/project-monster-attack) sample for how you are intended to make your game. If you run into problems with that approach, feel free to ask, but if the first thing you do is to try to do everything differently, then you are just making it harder for everyone.

**Comment by brightening-eyes** [comment]
yes. ezRendererDX11 was built and I have its library in output\lib\WinVS2022 folder
in the output folder in lib in WinVS2022 I have those libs built.
I assume if its built as a shared one, another exp file were need to be created beside it.
I used the asteroids sample and modified it.
another thing is, when I run the asteroids itself, it complains about sdk root directory which I managed to avoid it from within my game by using ezOSFile::GetCurrentWorkingDirectory() as the second argument to ezGameApplication's constructor.
even I run the ezplayer itself, it complains about sdk root directory.
I am using ezengine as a submodule of my game.

**Comment by jankrassnigg** [comment]
Then it's not about static linking.
Did you follow these steps ?
https://ezengine.net/pages/docs/build/submodule.html

If so, can you try to reproduce the same thing with this sample ?
https://github.com/ezEngine/submodule-example

Because if that has the same issue, than it's something outdated on our side. If that works, though, then you can see where your setup differs.

**Comment by brightening-eyes** [comment]
hello,
instead of using ezGameApplication stuff, if I use the HelloWorldApp.cpp of hello example in ezengine, it works and prints.
but as soon as I switch into ezGameState, it starts complaining:
here is my gameState.h:
```
#pragma once

#include <Core/Utils/Blackboard.h>
#include <GameEngine/GameState/GameState.h>

class gameState: public ezGameState
{
EZ_ADD_DYNAMIC_REFLECTION(gameState, ezGameState);

public:
gameState();
~gameState();
virtual void ProcessInput() override;

protected:
virtual void ConfigureInputActions() override;

private:
virtual void OnActivation(ezWorld* pWorld, const ezTransform* pStartPosition) override;
virtual void OnDeactivation() override;
virtual void BeforeWorldUpdate() override;
virtual ezGameStatePriority DeterminePriority(ezWorld* pWorld) const override;

private:
ezSharedPtr<ezBlackboard> m_pGlobalBlackboard;
};

```
and here is the gameState.cpp file:
```
#include "gameState.h"

#include <Core/Input/DeviceTypes/Controller.h>
#include <Core/System/ControllerInput.h>
#include <Core/System/Window.h>
#include <GameEngine/GameApplication/GameApplication.h>
#include <GameEngine/Gameplay/BlackboardComponent.h>
#include <Foundation/IO/OSFile.h>

EZ_BEGIN_DYNAMIC_REFLECTED_TYPE(gameState, 1, ezRTTIDefaultAllocator<gameState>)
EZ_END_DYNAMIC_REFLECTED_TYPE;

gameState::gameState()
{
ezHashedString globalsname;
globalsname.Assign("globals");
m_pGlobalBlackboard = ezBlackboard::GetOrCreateGlobal(globalsname);
ezHashedString hs;
hs.Assign("gameState");
m_pGlobalBlackboard->SetEntryValue(hs, 0);
}

gameState::~gameState()
{

}

void gameState::OnActivation(ezWorld* pWorld, const ezTransform* pStartPosition)
{
SUPER::OnActivation(pWorld, pStartPosition);
}

void gameState::OnDeactivation()
{
SUPER::OnDeactivation();
}

void gameState::BeforeWorldUpdate()
{

}

ezGameStatePriority gameState::DeterminePriority(ezWorld* pWorld) const
{
return ezGameStatePriority::Default;
}

void gameState::ConfigureInputActions()
{

}

void gameState::ProcessInput()
{

}

EZ_APPLICATION_ENTRY_POINT(ezGameApplication, "my test game", ezOSFile::GetCurrentWorkingDirectory());

```
now, I am going  to  build as shared libraries and check weather the issue is really from static library or from within my setup.

**Comment by jankrassnigg** [comment]
The fact that it complains about the root folder is probably the core issue, because if that path is wrong, it can't find anything.

I just remembered that we have some documentation about this:
https://ezengine.net/pages/docs/build/sdk-root.html

**Comment by brightening-eyes** [comment]
hello,
the issue seems with the static library.
when I built ezengine as dynamic libraries, the renderer for dx11 could be loaded.
although I set my current working directory for ezGameApplication, it again complained that it could not find the sdk root. I created ezSdkRoot.txt and then same error
copied the data directory alongside my output executable then it ran.
some things:
* for loading texture which it complains when loading, maybe someone does not want any texture. I suppose it should be an option to disable it or so. (I am working on an audio game and I might not need the rendering stuff at all). and this renderer dx11 is for my window creations.
* it should be possible to change the title from ezengine to something else (maybe I did something wrong)? because the project name does not change it.
* also for command line stuff, maybe someone does not need it. the same is true for keys like take screenshot (very useful for debugging). but for my own needs, its not needed (is there any way to completely disable these through code)?
* is there a way possible to change the key from escape to something else (maybe alt+f4) when quitting the ezGameApplication?
* when ezengine was linked dynamically, it easily could load up renderer dx11. so, I assume there is something wrong either with my setup, or with how ezengine loads plugins.
* another thing is when I set the sdk root directory through my game state's constructor, it does not take it into account and it complains about it. is it set in ezGameApplication?
thanks for all your help.

**Comment by jankrassnigg** [comment]
* Does your ezSdkRoot.txt also contain the correct path inside it? (see documentation)
* You can put a breakpoint into ezFileSystem::DetectSdkRootDirectory() and step through it to see what's going on.

>maybe someone does not want any texture

if you are making an audio only game, that is an extreme outlier. Doesn't make sense to add an option for that.

> it should be possible to change the title from ezengine to something else

Are you talking about the exe name, the window title or something else. All of those can be changed. I guess you mean the window title. See ezWindowCreationDesc there is an m_Title member, which is typically loaded from a config file. You can edit that file through the editor, or manually.

See ezGameState::CreateMainWindow() for where the config file gets loaded, you can also hardcode your title by overriding that function.

> keys like take screenshot 

See `ezGameApplication::Init_ConfigureInput()` it is where the standard keybindings are set up. You can derive from ezGameApplication and override that function to implement your own. Same for the escape key. `Alt+F4` is possible, but you can't register key combinations, so you would need to check for both keys individually.

> when ezengine was linked dynamically, it easily could load up renderer dx11. so, I assume there is something wrong either with my setup, or with how ezengine loads plugins.

When you link statically, there is no renderer DLL, at all. So the entire call to LoadPlugin is pointless, it will never find a DLL. It also doesn't need to, because it is already linked in. We could probably just wrap that LoadPlugin call with `#if EZ_ENABLED(EZ_COMPILE_ENGINE_AS_DLL)` to just skip it.

> another thing is when I set the sdk root directory through my game state's constructor, it does not take it into account and it complains about it. is it set in ezGameApplication?

Hm, don't know, would need to debug through it, what it is exactly doing. Generally if you have the ezSdkRoot.txt in the correct folder with the correct content, you should not need to specify that path anywhere else. It might be that you are now trying multiple ways to set the value and of course only one of them will be used in the end.

**Comment by brightening-eyes** [comment]
my ezSDKRoot.txt points exactly to the main directory of ezengine and the directory exists.
about linking rendererDX11 as dynamic library, it should load them. but when its linked statically, the linker may get rid of it somehow.
for changing title, I will override ezGameState::ConfigureMainWindow() thanks.
maybe for sdk root directory, I am doing it wrong. because as second argument to ezGameApplication, I set ezOSFile::GetCurrentWorkingDirectory() and it overrided ezSdkRoot.txt
thanks for your time and help.

**Comment by brightening-eyes** [comment]
hi again,
I can confirm that if the issue is with static lib
when I compile ezengine with my project as a submodule as a shared library, my project loads it fairly well, my window pops up fine (I even modified it as per my needs). but as soon as I compile as static library (which links RendererDX11 along with ezCore and ezFoundation directly into executable), it fails and gives that assert that I copied in the first message.
the reason that I am doing it is that I want to make my binary less dependent on other libraries, in order to be distributed easier.

**Comment by jankrassnigg** [comment]
As I [wrote above](https://github.com/ezEngine/ezEngine/issues/1294#issuecomment-2112365524) calling `LoadPlugin()` at all, doesn't make sense when you are linking statically. There is no DLL that it could find.

**Comment by brightening-eyes** [comment]
the issue is that ezengine\Code\Engine\RendererFoundation\Device\Implementation\DeviceFactory.cpp calls it on line 22 in order to load rendererDX11

**Comment by Sanakan8472** [comment]
So when EZ is compiled statically, all plugins are technically loaded at exe startup. There are some init functions that still need to be called for proper initilization, which is done by `ezPlugin::InitializeStaticallyLinkedPlugins`. A later call to `ezPlugin::LoadPlugin` won't do much except for checking that the plugin was already statically linked and loaded at startup. If this function fails, it means that the plugin was optimized away by the linker. You can easily verify this by putting a breakpoint into *Code/Engine/RendererDX11/RendererDX11PCH.cpp* at the start of `EZ_STATICLINK_LIBRARY(RendererDX11)`. If the breakpoint is not hit, the library is optimized away.
As I mentioned, you need to ensure that the library is needed by the exe at compile time or the linker gets rid of it. Have you tried what I suggested to call the function that `EZ_STATICLINK_LIBRARY(RendererDX11)` generates manually from your `main` function?
Something linke this should do the trick:
```
extern "C" void ezReferenceFunction_RendererDX11(bool bReturn = true);
...
// Call in any function that is not optimized away:
ezReferenceFunction_RendererDX11(false);
```
Not that when statically linked, the ability to load dynamic plugins is currently removed as the assumption is that you either built everything statically or dynamically. So if a `ezRendererDX11.dll` exists, it won't be loadable by a static build of EZ. You would need to ensire that every library is built statically instead.

**Comment by brightening-eyes** [comment]
hello,
during compilation, it works fine and the cpp sources compile into object files. but when linking, there are 2 undefined references:
```
ezRendererDX11.lib(RendererDX11PCH.obj) : error LNK2019: unresolved external symbol ezReferenceFunction_RendererDX11_Context_Implementation_ContextDX11 referenced in function ezReferenceFunction_RendererDX11
```
and
```
ezRendererDX11.lib(RendererDX11PCH.obj) : error LNK2019: unresolved external symbol ezReferenceFunction_RendererDX11_Resources_Implementation_FenceDX11 referenced in function ezReferenceFunction_RendererDX11
```
thanks

**Comment by Sanakan8472** [comment]
This should fix it https://github.com/ezEngine/ezEngine/pull/1295.
Note that to ensure no parts of a static lib a stripped, we run the [StaticLinkUtil](https://ezengine.net/pages/docs/tools/staticlinkutil.html). We haven't done that in a while for the DX11 plugin as we didn't need to run static builds. If you encounter the same problem on another library, just follow the instructions in the docs.

**Comment by brightening-eyes** [comment]
hello,
@Sanakan8472
with the pull request that you proposed, the issue completely got fixed. I didn't know that it could be caused by the static link references. thanks.
I'm closing this.
