### ISSUE TITLE
[FEATURE] Non-assignment Vector3 multiplication/divide is missing

### ISSUE THREAD

**Issue by RiederAlex** [ezEngine/ezEngine#1304]
As a user, I often want to do stuff like:

```
float scalar;
ezVec3 vector1,vector2;
ezVec3 result = (vector1 * vector2) * scalar;
```
However, currently I would have to write:
```
float scalar;
ezVec3 vector1,vector2;
ezVec3 result = vector1;
result *= vector2;
result *= scalar;
```

Is there a reason I'm not aware of as to why this is not implemented for Vec3.h (and Vec2.h)?
Otherwise I would do a PR implementing these.

**Comment by jankrassnigg** [comment]
*= with a vec3 shouldn't even work. If it does, that's not intended. 

The problem with vec*vec is, that it isn't clear what it should do. Some people expect it to be component wise, some expect it to be dot product. 
Therefore we simply don't provide it at all.

**Comment by C-Core** [comment]
I guess you want component wise multiplication? Then use the CompMul function.

**Comment by RiederAlex** [comment]
*= with a vec3 is even implemented here (Vec3_inl.h, L 198)

```
template <typename Type>
EZ_FORCE_INLINE void ezVec3Template<Type>::operator*=(const ezVec3Template& rhs)
{
  /// \test this is new

  x *= rhs.x;
  y *= rhs.y;
  z *= rhs.z;

  EZ_NAN_ASSERT(this);
}
```

so I guess this is not intended then?

However, for me much more important is the scalar multiplication - e.g. Vec3 * Float - as one scales stuff by delta and/or by some other constant - is this something that would be acceptable to implement?

**Comment by jankrassnigg** [comment]
Not sure about the *=. I guess it's less of an issue, because dot product doesn't make sense here. 

Scalar*vec should already work. Vec/scalar as well. Iirc `vec*scalar` doesn't work because of stupid c++ rules or something like that. Or maybe what I'm thinking about is `vec*int`. Anyway, fine with me to add those.

**Comment by RiederAlex** [comment]
Closing this issue - as `CompMul` does what I want and implementing ```vec*int``` would require some template magic I'd rather avoid, so I'll resort to casting int to float manually.
