### ISSUE TITLE
[FEATURE] Data structure for nearest neighbor search in 2D/3D

### ISSUE THREAD

**Issue by x0r04rg** [ezEngine/ezEngine#1333]
**Is your feature request related to a problem? Please describe:**
It's quite common in games to query for a nearest object of some type. For example, a worker in a RTS, when assigned a wood harvesting task, would want to query for the nearest tree. 
ezEngine already provides a lot of useful data structures meant to be used as building blocks, so adding this one seems in line with the order of things.

**Describe the solution you'd like:**
I think a reasonable solution would be to add nn search methods to ezDynamicOctree/Quadtree. A dedicated data structure specifically for this problem (e.g. k-d tree) is also a good solution, but is more work.

**Comment by jankrassnigg** [comment]
Good news everyone! We already have this:
https://ezengine.net/pages/docs/runtime/world/spatial-system.html

**Comment by x0r04rg** [comment]
But it's not the same. Spatial system allows me to perform queries like "give me all objects of type X in radius R", but this issue is about "give me the object of type X that is the nearest one to point P" - key difference is that I don't specify the range here, because I don't know what it could be

**Comment by jankrassnigg** [comment]
Well, in a game you basically always have some maximum range. You don't want to get a point that's 1000 meters away, because it would take too long to walk there. 

Just do a query with a sensible radius. If it can be very big, start with a small radius, to not waste performance, and do a larger query if the first one yields no results.

**Comment by x0r04rg** [comment]
I guess you are right. I've already thought about doing multiple searches with increasing ranges but concluded it would waste too much performance. But now that I think of it again, failed searches (ones that don't find anything) should be almost free with an octree.

Sorry for bothering!

**Comment by jankrassnigg** [comment]
All good, have fun.
