### ISSUE TITLE
Asset transform does not detect error state correctly anymore

### ISSUE THREAD

**Issue by jakrams** [ezEngine/ezEngine#135]
* Make any incorrect dependency in an asset (ie. incorrect texture file reference in material).
* Enable background processing
* Watch AssetCurator
-> it will try to transform the broken asset multiple times, never failing

If the asset is a dependency of other assets, this will also block processing of those assets.

**Comment by Sanakan8472** [comment]
I think I have fixed this in pull request #197 from ezEngine/user/cm/assetCurator_fixes
@jankrassnigg If you find another repro case now, please re-open, thanks!
