### ISSUE TITLE
[BUG] File System Watcher on Windows fails to send rename notifications

### ISSUE THREAD

**Issue by jankrassnigg** [ezEngine/ezEngine#1366]
We use the filesystem watcher to detect when git operations are in progress. This is guarded with ".lock" files. So whenever a lock file appears we know that a git operation is in progress.

There are operations (staging a file) that do file access operations that are not properly reported:

![image](https://github.com/user-attachments/assets/5552c3e2-106e-4584-a34c-f6e235167f88)

This is the log output using DEBUG_FILE_WATCHER in DirectoryWatcher_win.cpp.

Here git creates an "index.lock" file, then it deletes any previously existing "index" file, then renames the "index.lock" to just "index" and keeps it around.

The filesystem watcher only reports the creation of "index.lock". It does not report the renaming of "index.lock" to "index". So from our perspective, the file never got "removed".

**Comment by jankrassnigg** [comment]
@Sanakan8472 maybe you have an idea why this happens?

**Comment by Sanakan8472** [comment]
@jankrassnigg need to check. There is a quirk that Windows sends a delete message when renaming a file with only casing changes. So rename + delete must be handled in a special way. Maybe the logic is bad? I suppose I can test this with just ay git command? Is this NTFS ?

**Comment by jankrassnigg** [comment]
Yes NTFS. You can test this by watching a .git folder and then staging a file in fork. That produces this weird pattern.
