### ISSUE TITLE
[BUG] ezFileSystem::GetFileReader impl seems wrong in case bAllowFileEvents=false is passed

### ISSUE THREAD

**Issue by FlorianBorn71** [ezEngine/ezEngine#1395]
**Bug description:**
To be clear: I haven't tested this and I'm also not blocked by this, but it struck my eyes when I stepped through the code.

Look into the loop inside ezFileSystem::GetFileReader that tests all data directories. It tries to get the reader:

ezDataDirectoryReader* pReader = ...
(line 498 in my checkout)

but the (valid) pReader is never returned in the bAllowFileEvents==false case. Instead it proceeds to the error case.

**Comment by jankrassnigg** [comment]
Indeed. It's a quick fix, will include it in a later PR.

Thanks for letting me know :)
