### ISSUE TITLE
Crash in DeleteDeadObjects

### ISSUE THREAD

**Issue by jankrassnigg** [ezEngine/ezEngine#149]
Transforming a scene I regularly get a crash in the ezWorld. See this:

![image](https://user-images.githubusercontent.com/6001174/76110883-9a579c00-5fdf-11ea-87b5-ad1763a6e6e9.png)

It seems as if 'this' is an invalid / new object that has not been used or setup before, whereas 'other' is a regular (now dead) object that is supposed to be copied over 'this'. The assert now complains that the worlds differ. This looks like a false positive to me.

This happens pretty consistently and often for me since the last MSFT merge...

**Comment by C-Core** [comment]
I've tried to reproduce this issue but instead I constantly run into a deadlock in transform all or when transforming a scene

![TransformAllDeadlock](https://user-images.githubusercontent.com/9219412/76121181-638b8100-5ff3-11ea-81b3-33e77f511391.png)
