### ISSUE TITLE
Decals with long extents start to fade out again

### ISSUE THREAD

**Issue by jankrassnigg** [ezEngine/ezEngine#179]
Create a decal with extents (2, 0.5 0.5,) and let it intersect with a wall. Now scale the X extent up more and more. You will see the decal fade out again at some point, even though the decals should have full strength.

**Comment by C-Core** [comment]
We decided to ignore this problem since it is a rare use case and it would require a second matrix in the decal data to fix it. Since the decal data is already quite large we don't want to add more stuff in there.
