### ISSUE TITLE
Community: Communication channel

### ISSUE THREAD

**Issue by jayrulez** [ezEngine/ezEngine#194]
Is there a communication channel that I can use to ask questions about the engine?

I have a few questions and maybe follow-ups in the future but I do not want to clutter the issue tracker with such questions.

Are the devs on discord, gitter, or any other community platform?

**Comment by jankrassnigg** [comment]
So far we don't have any such channel, as it wasn't need yet. If you have suggestions what works well in your experience, let us know and we'll look into it. For the time being, just ask away through GitHub issues.

**Comment by jankrassnigg** [comment]
Ah well, let's just try this out:

https://gitter.im/ezEngine/community#share

**Comment by jankrassnigg** [comment]
Fixed: https://ezengine.github.io/docs/appendix/contact.html
