### ISSUE TITLE
Editor: Log search filter UI issue

### ISSUE THREAD

**Issue by jayrulez** [ezEngine/ezEngine#195]
When a category is selected in the log search section the messages for the category are shown but empty rows remain for messages from other categories.

All categories:
![image](https://user-images.githubusercontent.com/78807/79791716-c757d800-831b-11ea-883e-c0019b2daa0a.png)

![image](https://user-images.githubusercontent.com/78807/79791757-d50d5d80-831b-11ea-91b2-64bfb765fbe6.png)

**Comment by jankrassnigg** [comment]
Interesting, I have never noticed this behavior. I am trying to reproduce this, and I can see that in very few cases there is an empty line, but I haven't managed to get more than 3 in total, and usually they are either at the beginning or the end of the log. Can you reproduce this reliably? If so, which scene are you using and exactly what steps are you doing?

**Comment by jayrulez** [comment]
It seems I am not able to reproduce it consistently since I reloaded the project. But If you have a component that does some logging every frame maybe you could.

Try logging to different categories from the component and run it for a few seconds then try filtering them.

**Comment by jankrassnigg** [comment]
@jayrulez the problem should be fixed now. Reopen the ticket please, if you can still reproduce.
