### ISSUE TITLE
Asset Transform Deadlock

### ISSUE THREAD

**Issue by jankrassnigg** [ezEngine/ezEngine#209]
![image](https://user-images.githubusercontent.com/6001174/80678412-286d7180-8abb-11ea-9152-5fe7087b0341.png)

[Editor.zip](https://github.com/ezEngine/ezEngine/files/4556432/Editor.zip)

Built from 2b745c401cb54778eb14aeaa8e5da11b32de3e90

Steps taken: Create a new asset (collision mesh), transform it manually (CTRL+E). Seems like it deadlocks because it also saves the asset first.

**Comment by Sanakan8472** [comment]
This is an odd one. There 8 tasks waiting for the curator mutex: Filewatcher update, asset update and 6 transform tasks to query for new work. Those take up all task threads so the main thread waiting for a task to finish under the curator mutex never finishes. I can move the save out of the lock scope but I wonder whether the transform tasks occupying threads might cause problems down the line again.
