### ISSUE TITLE
Getting this "Invalid Camera Mode {0}"when using Player executable or hitting Play In Game button for Testing Chambers.

### ISSUE THREAD

**Issue by antonyjones67** [ezEngine/ezEngine#249]
If you push through the Assert in the Player executable, it eventually sets the Camera Mode, but the screen is still Black. In the Editor it does seem to work. But the Assert is annoying.

**Comment by jankrassnigg** [comment]
Fixed by commit 1be71e7354d43419c885c11b47981d888c8674d9
