### ISSUE TITLE
Black screen when running Testing Chambers\Corridor.ezScene through Player executable.

### ISSUE THREAD

**Issue by antonyjones67** [ezEngine/ezEngine#252]
When executing Player with parameters-scene "D:\Dev\ezEngine\Data\Samples\Testing Chambers\ezProject\Corridor.ezScene" gives me a black screen.

This is currently working through Editor.

**Comment by jayrulez** [comment]
If you connect the inspector to the running instance of the player, you might see this line being hit:
https://github.com/ezEngine/ezEngine/blob/dev/Code/Tools/Player/Main.cpp#L109

**Comment by jankrassnigg** [comment]
You need to export the scene first. See http://ezengine.net/editor/run-scene.html (at the bottom) for details.

![image](https://user-images.githubusercontent.com/6001174/82787182-2d2d0780-9e66-11ea-8fa3-e9adadebd1a2.png)

"Export" will appear to do nothing (the screen just flickers briefly), as it's quite quick to finish, but it is important.

This workflow is not intuitive. I created #253 as a work item to improve it.

Thanks for the feedback !
