### ISSUE TITLE
When going from maximized to not maximized causes strange visual glitches happen in QT.

### ISSUE THREAD

**Issue by antonyjones67** [ezEngine/ezEngine#254]
![WierdDisplayGlitchWithQT](https://user-images.githubusercontent.com/3905646/82791215-968f2500-9e2a-11ea-8fe6-8241bbdfc2af.jpg)

**Bug description:**
When going from maximized to not maximized causes strange visual glitches happen in QT.

**Dev-branch commit hash:**
Date:			11 hours ago (5/24/2020 2:24:56 PM)
Commit hash:	1be71e7354d43419c885c11b47981d888c8674d9
Parent:			e4d783469d
Master

Windows 10
NVIDIA 1060 GTX. Latest Video Drivers.

**Comment by antonyjones67** [comment]
I should probably mention that I am using Qt 5.14.2.

**Comment by antonyjones67** [comment]
Seems to fix everything if I completely minimize the window, and un-minimize it.

**Comment by jankrassnigg** [comment]
I can't reproduce this at the moment. If you feel like investigating, you could 1) use the dev branch and 2) compare it with our provided Qt libraries, which use an older version.

If the Qt version makes a difference, this may be a problem with the docking framework.

**Comment by antonyjones67** [comment]
I ran the precompiled binaries and I did not experience the problem with QT. What version of QT are you compiling against? BTW thank you for all the help you have been giving me.

**Comment by jankrassnigg** [comment]
The precompiled libs are version 5.13.0. Unfortunately it's not uncommon that new Qt versions break things here and there.

We use this for the docking framework: https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System

Not sure with what Qt version this is supposed to work, though.

Personally, I don't have the time atm to dig into this, but if you want to continue, you could try to reproduce it with the sample app from that project. Another option is of course to just ignore the problem for now and assume it gets fixed some way sooner or later :D

**Comment by antonyjones67** [comment]
I updated QT 5.14.2 to 5.14.2+, and it seems to have been fixed the problem. Thank you.

**Comment by antonyjones67** [comment]
Sorry. It seemed to fix it temporarily. It is still an open issue. My bad.

**Comment by antonyjones67** [comment]
I back tracked QT 5.13.2 it looks like it resolved the QT issues. Thank you.
