### ISSUE TITLE
[FEATURE] Сameras

### ISSUE THREAD

**Issue by gdserds** [ezEngine/ezEngine#278]
Hello! Can you add the ability to create your own cameras in the next version of your engine? For example, a third-person camera, or just a camera that is flying somewhere. This would be very useful, especially if you added the ability to customize them visually (such as your physics settings). I hope so! Good luck!

**Comment by jankrassnigg** [comment]
You can already create your own cameras. See the documentation:
http://ezengine.net/graphics/camera-component.html

Or did you have something else in mind?
