### ISSUE TITLE
[BUG] Bounding(Box)Sphere set radius to -1, which doesn't work with ExpandToInclude

### ISSUE THREAD

**Issue by jankrassnigg** [ezEngine/ezEngine#314]
ezBoundingSphere and ezBoundingBoxSphere::SetInvalid() set the radius to -1.

Using this with ExpandToInclude(vertex) with a vertex that is closer than 1 unit, fails to grow the box, because the sphere uses the squared radius to determine how much to grow. Since sqr(-1) is 1, it thinks it doesn't need to grow.

This can result in crashes in places that expect a valid bounding sphere.

**Comment by C-Core** [comment]
If this issue gets fixed also verify that it works correctly in ezBoundingBoxSphere and in ezSimdBSphere and ezSimdBBoxSphere
