### ISSUE TITLE
3d view in editor does not display correctly on second monitor.

### ISSUE THREAD

**Issue by antonyjones67** [ezEngine/ezEngine#339]
**Bug description:**
If you drag the editor to a secondary monitor the 3d view does not display correctly.

**How to Reproduce:**
1. Run Editor.
2. Drag Editor to second monitor.

![dualmonitorbug](https://user-images.githubusercontent.com/3905646/96302914-cd6efe80-0fb6-11eb-843a-82dd26502c52.jpg)

Branch jk/anim--controller - commit hash a937e5320a169f8d07e7c1e95db7ab5f6ac6702b

**Comment by jankrassnigg** [comment]
It looks as if the 3D view got lost entirely. Unfortunately I can't reproduce this.

Do your monitors have different resolutions? I use full HD on both of mine. Did you try in a Debug build with debugger attached (to all child processes, see http://ezengine.net/debugging/debug-cpp.html). It would be interesting, whether D3D maybe prints an error, which tells us, what's happening.

Also, which Qt version do you use? The one that comes with ez?

**Comment by jayrulez** [comment]
I was not able to reproduce this using 2 monitors at different resolutions. However, when going from the higher to the lower the application window does not resize to fit the lower and large portions end up offscreen on the lower res monitor.

**Comment by antonyjones67** [comment]
This hasn't been a problem for me lately.
