### ISSUE TITLE
[FEATURE]Add line thickness as a parameter for ezDebugRenderer::Line()

### ISSUE THREAD

**Issue by antonyjones67** [ezEngine/ezEngine#354]
Would like to be able to draw debug lines with varying thickness.
Thank you.

**Comment by jankrassnigg** [comment]
Unfortunately that's a feature that graphics APIs like DX11 don't support anymore. One would need to implement a feature like that with special shaders, and that can be quite tricky. For debug rendering we don't intend to support this.

If you actually want to do thick lines for proper game stuff, the requirements might be different. It might be easier to render actual geometry like pipes or quads.

**Comment by antonyjones67** [comment]
Okay thank you. :)
