### ISSUE TITLE
[BUG]Adding component to game object can crash the editor

### ISSUE THREAD

**Issue by jayrulez** [ezEngine/ezEngine#359]
**Bug description:**
Under certain behaviour, the editor will crash and exit while adding a component to a game object.

**How to Reproduce:**
Click on the game object in the scene graph window.
Click "Add Item to add a component"
Invoke a filter (searching for component by typing name) and quickly double click the component as soon as it appears.
The editor will crash and exit.

**Dev-branch commit hash:**
7de92632c920716770b06a2745f8ae5181b07ef8

**Comment by jankrassnigg** [comment]
I have trouble replicating this. Can you tell me WHICH component type you used? Maybe it is related to that.

**Comment by jankrassnigg** [comment]
Closing this for now, please reopen if you can still reproduce this.
