### ISSUE TITLE
It would be nice to have a "Shipping" build configuration.

### ISSUE THREAD

**Issue by antonyjones67** [ezEngine/ezEngine#367]
It would be nice to have a "Shipping" build configuration.

**Comment by jankrassnigg** [comment]
How do you mean that? A Release build is what you should use for shipping.

**Comment by antonyjones67** [comment]
I would like to run optimized code, but have a mechanism to remove code profiling for instance.
Just as an example, I will use Unreal.
Unreal has:
Debug - Full Debug Build
DebugGame : Engine Optimized & Game Debug
Development: Full Release Build. Editor & Profiling defined in.
Shipping: Full Release. Editor & Profiling defined out.
