### ISSUE TITLE
[FEATURE] DebugRenderer ordered text rendering

### ISSUE THREAD

**Issue by jankrassnigg** [ezEngine/ezEngine#470]
The DebugRenderer should have a mode to add text to the screen, which automatically places the text in a non-overlapping position with other text.

E.g. append text, maybe structured in a hierarchy.

**Comment by C-Core** [comment]
What would be the use case? This would require full text layouting which is beyond the scope of the debug renderer I think.

**Comment by jankrassnigg** [comment]
The use case would be to enable multiple debug outputs and have them automatically show up below each other, daher than having to guess a good position for each. Also it would be resolution independent. 

I don't intend to do layouting, but rather a very simply mechanism of specifying a screen corner as the anchor and then draw the strings beneath each other there.  There might still be overlap, but printing 10 different things on screen would still be easier. 

For example the camera stats would be a use case. Actually basically everything that currently does Draw2DText.

**Comment by jankrassnigg** [comment]
Fixed by #473
