### ISSUE TITLE
[BUG] ADVAPI32.dll error

### ISSUE THREAD

**Issue by erfansst** [ezEngine/ezEngine#482]
Hi my friends, I got an error when opening the ez engine, which you can see below
[https://s4.uupload.ir/files/error_95vj.bmp](url)
Please anyone who runs the engine send me their ADVAPI32.dll file from the c: // windows / system32 / folder. Thank you.

**Comment by jayrulez** [comment]
Windows 7 is not supported.

**Comment by jankrassnigg** [comment]
Indeed, you are running windows 7, right? We only support windows 10.

**Comment by erfansst** [comment]
OK , thanks friends
