### ISSUE TITLE
[FEATURE] It would be nice to be able to see Skylight directional arrow represented in all the viewports.

### ISSUE THREAD

**Issue by antonyjones67** [ezEngine/ezEngine#517]
It would be nice to be able to see Skylight directional arrow represented in all the viewports. So you can see the direction the Skylight is pointing from additional directions.

![SkyLightDirectionalArrow](https://user-images.githubusercontent.com/3905646/145701719-ec344cfd-ea8e-41fe-844e-a38ebfb3bc76.png)

**Comment by jankrassnigg** [comment]
@antonyjones67 you could try out, whether it all works as expected now. I've changed other visualizers as well, should all be better now.
