### ISSUE TITLE
[BUG] cmake build error

### ISSUE THREAD

**Issue by SailorLou** [ezEngine/ezEngine#518]
Hi Expert,
when i use cmake to build this project ,an cmake error :
CMake Error at Code/EnginePlugins/PhysXCooking/CMakeLists.txt:6 (ez_requires_physx):
  Unknown CMake command "ez_requires_physx".

i don't find the definition of ez_requires_physx , ez_requires_fod...

 please help take a look ,
thanks
Best Wishes
Sailor

**Comment by jankrassnigg** [comment]
You need to update the git submodules first, fmod and physx are not in the main repository.
git submodule init
git submodule update

**Comment by SailorLou** [comment]
thanks
