### ISSUE TITLE
Would love to see a message handler on the Animation Controller, similar to OnScriptUpdate on the VisualScript asset.

### ISSUE THREAD

**Issue by antonyjones67** [ezEngine/ezEngine#564]
Would love to see a message handler on the Animation Controller, similar to OnScriptUpdate on the VisualScript asset.
Would love  to be able write my own event handlers in the Animation Controller. Maybe even go as far as delegate usage.

**Comment by jankrassnigg** [comment]
Should be possible. What type of events are you interested in? Just genetically "after update" or is there anything else? What kind of use case do you have in mind?

**Comment by antonyjones67** [comment]
Just a simple "update" would be fine. I am cool with anything.  Thank you.
