### ISSUE TITLE
StackTracer issue with Unreal Engine

### ISSUE THREAD

**Issue by DOCaCola** [ezEngine/ezEngine#567]
For the longest time i have been wondering why MemoryTracker wouldn't report a human readable stacktrace when reporting memory dumps. I took the time to investigate and it appers that the call to SymInitializeW fails (SymbolInitialize function in StackerTracer_win.h).
The reason appears that Unreal Engine interferes by loading and using dbghelp.dll as well. Probably for their crash reporter.
When ez tries to call SymInitializeW it fails with error code 87.
I figured that when SymInitializeW fails, probably because it was already called by unreal, i instead call debughlp.dll's SymRefreshModuleList the MemoryTrackers' stack trace now correctly works again.

My workaroundy changes to StackTracer_win.h currently look like this:

`refreshModules = (RefreshModulesFunc)GetProcAddress(dbgHelpDll, "SymRefreshModuleList");`
...
```
  static void SymbolInitialize()
  {
    if (!s_pImplementation->m_bInitDbgHelp)
    {
      s_pImplementation->m_bInitDbgHelp = true;
      if (!(*s_pImplementation->symbolInitialize)(GetCurrentProcess(), nullptr, TRUE))
      {
        //ezLog::Error("StackTracer could not initialize symbols. Error-Code {0}", ezArgErrorCode(::GetLastError()));
        (*s_pImplementation->refreshModules)(GetCurrentProcess());
      }
    }
  }
```

I wonder if this could also be related to the issue described in the code comment in ezStackTrace::OnPluginEvent. Instead of trying to call SymInitialize as late as possible to instead call it early and SymRefreshModuleList later on.

**Comment by C-Core** [comment]
I will take a look at it at some point
