### ISSUE TITLE
Crash when trying to click on move/rotate/scale manipulators buttons in toolbar. 

### ISSUE THREAD

**Issue by antonyjones67** [ezEngine/ezEngine#571]
Crash when trying to click on move/rotate/scale manipulators buttons in toolbar. 

Looks like parameter passed into IsActiveEditTool() is nullptr no matter what button I select.

Callstack.
>	ezFoundation.dll!ezReflectedClass::IsInstanceOf(const ezRTTI * pType) Line 8	C++
 	ezEditorFramework.dll!ezGameObjectDocument::IsActiveEditTool(const ezRTTI * pEditToolType) Line 90	C++
 	ezEditorFramework.dll!ezGizmoAction::UpdateState() Line 44	C++
 	ezEditorFramework.dll!ezGizmoAction::GameObjectEventHandler(const ezGameObjectEvent & e) Line 51	C++
 	ezEditorFramework.dll!ezDelegate<void __cdecl(ezGameObjectEvent const &),16>::DispatchToMethod<void (__cdecl ezGizmoAction::*)(ezGameObjectEvent const &),ezGizmoAction>(const ezDelegate<void __cdecl(ezGameObjectEvent const &),16> & self, const ezGameObjectEvent & <params_0>) Line 293	C++
 	ezEditorFramework.dll!ezDelegate<void __cdecl(ezGameObjectEvent const &),16>::operator()(const ezGameObjectEvent & <params_0>) Line 210	C++
 	ezEditorFramework.dll!ezEventBase<ezGameObjectEvent const &,ezNoMutex,0>::Broadcast(const ezGameObjectEvent & eventData, unsigned char uiMaxRecursionDepth) Line 209	C++
 	ezEditorFramework.dll!ezGameObjectDocument::SetActiveEditTool(const ezRTTI * pEditToolType) Line 137	C++
 	ezEditorFramework.dll!ezGizmoAction::Execute(const ezVariant & value) Line 39	C++
 	ezEditorFramework.dll!ezToggleWorldSpaceGizmo::Execute(const ezVariant & value) Line 71	C++
 	ezGuiFoundation.dll!ezQtButtonProxy::OnTriggered() Line 410	C++
 	ezGuiFoundation.dll!ezQtButtonProxy::qt_static_metacall(QObject * _o, QMetaObject::Call _c, int _id, void * * _a) Line 358	C++
 	[External Code]	
 	ezGuiFoundation.dll!ezQtProxy::TriggerDocumentAction::__l2::<lambda>(QKeyEvent * event, ezMap<ezActionDescriptorHandle,QWeakPointer<ezQtProxy>,ezCompareHelper<ezActionDescriptorHandle>,ezDefaultAllocatorWrapper> & actions) Line 114	C++
 	ezGuiFoundation.dll!ezQtProxy::TriggerDocumentAction(ezDocument * pDocument, QKeyEvent * event) Line 126	C++
 	ezGuiFoundation.dll!ezQtDocumentWindow::event(QEvent * event) Line 308	C++
 	[External Code]	
 	qwindowsd.dll!QWindowsGuiEventDispatcher::sendPostedEvents() Line 83	C++
 	[External Code]	
 	qwindowsd.dll!QWindowsGuiEventDispatcher::processEvents(QFlags<enum QEventLoop::ProcessEventsFlag> flags) Line 74	C++
 	[External Code]	
 	ezEditorFramework.dll!ezQtEditorApp::RunEditor() Line 35	C++
 	Editor.exe!ezEditorApplication::Run() Line 51	C++
 	ezFoundation.dll!ezRun_MainLoop(ezApplication * pApplicationInstance) Line 27	C++
 	ezFoundation.dll!ezRun(ezApplication * pApplicationInstance) Line 67	C++
 	Editor.exe!ezApplicationDetails::ApplicationEntry<ezEditorApplication>() Line 80	C++
 	Editor.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 63	C++
 	[External Code]	

Commit Hash.
9de5245954e6cdb45d82be302c990c58af11751b

**Comment by jankrassnigg** [comment]
Yes this was introduced by #570 and somehow slipped through the testing. Sorry about that.
Fixed in 54883a79a221511b612566aec680393550b12283.

**Comment by antonyjones67** [comment]
No problem. Thank you.

**Comment by antonyjones67** [comment]
Thanks for fixing that.
