### ISSUE TITLE
[BUG] Editor Crashes when a surface is selected as itself for BaseMaterial

### ISSUE THREAD

**Issue by exoad** [ezEngine/ezEngine#580]
**Bug description:**
The Editor refuses to launch and crashes if a Surface has its BaseMaterial Selected as itself.

**How to Reproduce:**
A clear description what steps to take to reproduce the issue.
1. Do this...
1. Do that...
1. etc...
Create a new Surface, then set the BaseMaterial property to itself.

I am on Windows 10 (x64)

**Comment by exoad** [comment]
Ok I was able to kind of fix this by deleting / renaming / moving my current project directory

**Comment by jankrassnigg** [comment]
Reopening, because this definitely needs a proper fix.

**Comment by exoad** [comment]
> Reopening, because this definitely needs a proper fix.

Were you able to reproduce this?

**Comment by jankrassnigg** [comment]
Unfortunately this can still happen.

Surfaces use only ezDependencyFlags::Package when referencing their base surface. Apparently this is not checked for circular dependencies and therefore it is possible to select something as its own base.

Materials on the other hand also use ezDependencyFlags::Thumbnail, which apparently prevents building circular dependencies.
