### ISSUE TITLE
Sometimes Content Browser filter does not filter as expected.

### ISSUE THREAD

**Issue by antonyjones67** [ezEngine/ezEngine#582]
Intel i-7
Windows 10
GPU-2070 Gtx

1. Select root in ContentBrowser.
2. Type "test" in ContentBrowser.
3. Notice that items without the word test in there names show up in the Content Browser.

If I were to guess, the filter code was unable to find anything with the word "test" and instead of showing no files, it shows files which seem to be more or less random.

Thank you!

![image](https://user-images.githubusercontent.com/3905646/166156572-74110a3c-d213-4894-9379-c1c9b82069f9.png)

**Comment by antonyjones67** [comment]
Actually I just added a file called "test" and the filter still did not work.

**Comment by jankrassnigg** [comment]
It filters by multiple sources, so not only the file name, but also the path. I'd have to check, but it might use the full absolute path. If that is the case, "test" might not work for you because you have the project installed into a folder with that in the path.

**Comment by jankrassnigg** [comment]
That would still be unintended behavior, though.
