### ISSUE TITLE
[FEATURE] Export Custom Executable

### ISSUE THREAD

**Issue by richard14110** [ezEngine/ezEngine#590]
**Is your feature request related to a problem? Please describe:**
ezEngine has the ability to create a .ezObjectGraph file but it is not a .exe file.

**Describe the solution you'd like:**
In the future, an in-editor build feature could simplify the compilation process for the user. When the "Export and Run..." dialog box appears, there should be the options to edit the name, icon, and path of the executable if the person wants to generate it for distribution and/or to test it on a different computer. Perhaps the .exe file can be a modified version of Player.exe and the required .dll files get copied and/or compiled to the output directory? I didn't find any documentation about how to build a sample to an executable with its dependencies on the website but I understand that it may be added later. There is documentation for making the engine and the editor.

**Additional context:**
Later, there may be more settings for different platforms.

**Comment by jankrassnigg** [comment]
Yes, this is a feature that i would like to add at some point. Currently there's indeed no automatic solution, and manually doing it is a bit complicated.

**Comment by TheFloatingBrain** [comment]
Hi, I know im just coming into the issues section barely knowing anything, but wanted to ask, could you generate a source file, embed the prefab file in it, then parse the prefab file at compile time using constexpr stuff? I have been doing a lot of work with ctpg. I haven't really dug into the engine code so feel free to ignore me :-)

**Comment by jankrassnigg** [comment]
That would require the entire engine to be constexpr, no? Which it obviously isn't. So I'd guess the answer is "no".

The more important question though is, what you think you want to achieve at compile time?

**Comment by TheFloatingBrain** [comment]
> That would require the entire engine to be constexpr, no? Which it obviously isn't. So I'd guess the answer is "no".
> 
> The more important question though is, what you think you want to achieve at compile time?

What I am inferring is that the the .ezObjectGraph is a file loaded at runtime alongside a generic executable with the engine (with the game loaded as a DLL).

What I am thinking is you could possibly achieve some optimizations by parsing the file and perhaps cutting off unnecessary steps (for that particular file) at compile time. For example, you could know the number of certain objects at compile time, and there may be optimizations around that and creating fixed sized arrays arrays of them, for example.

I'm kinda just jumping in here, so please forgive me if I sound rather foolish

**Comment by jankrassnigg** [comment]
Loading prefabs is very fast, there is really no need for such a rather complicated optimization. Also I don't think that it is even possible.
