### ISSUE TITLE
[FEATURE] Use Package Manager

### ISSUE THREAD

**Issue by TheFloatingBrain** [ezEngine/ezEngine#613]
**Is your feature request related to a problem? Please describe:**
I am trying to build on linux, it would probably be easier if I could use `conan` package manager (or vcpkg, but I use conan) to fetch all the dependencies.

**Describe the solution you'd like:**
The ability to use `conan` and/or `vcpkg` to build this project

**Additional context:**
#Upsides: 
- Conan and vcpkg make life a lot easier, with conan all I have to do is specify a `conanfile.txt` with the libraries I want/generator (cmake) and make a few minor modifications to CMakeLists.txt and it takes care of the rest, it can even look for some packages on my system, you can even create your own package quite easily (especially if you have customized anything). It works on Windows/Mac/Linux and would probably make the project easier to build, more platform independent and builds more easily repeatable without having to install a ton of stuff on a system.
- It can even be used to create isolated environments. The project itself  could be packaged, tools and everything could be built out of the box quite easily.
- For vcpkg, you simply just type #include <header> and if it has been installed/exposed with vcpkg, Visual Studio will automagically link it.

#Downsides: 
- Custom modification of 3rd party libraries is a bit harder, I have also noted a trend to use CMake fetch, which is a phenomenon I don't quite understand yet.
- If you want to keep the current CMakeLists.txt files it will require modifying them and may add a couple of branching paths (small amount of complexity).
- It is my understanding this project uses DX11, I have been thinking that perhaps to build on linux I may use a DX11 wrapper for Vulkan (this is done with WINE and is available). This would require non-declarative logic for the package manager/the creation of a package, or may require it to be added to the `ThirdParty` folder anyway (building using conditional logic)

**Comment by Ingrater** [comment]
I don't agree that moving to a nonstandard package manager like vcpkg or conan has significant benefits for us. There is currently no de-facto standard package manager for c++, so sticking with the OS package manager or internalizing the third party dependencies as we do currently is in my opinion the better option.

Also be careful with the work you are doing on linux. Linux support is currently under active development and a Vulkan renderer is being build, that is going to be used on linux and other platforms. So building DX11 on Linux won't help much at this point. We don't want to target WINE, we'd rather have "real" linux support.

**Comment by TheFloatingBrain** [comment]
Okay, I will work with that then, thanks for giving it your consideration :) :+1: 

Is there another fork with the experimental Vulkan renderer?

**Comment by jayrulez** [comment]
The Vulkan backend is here: https://github.com/ezEngine/ezEngine/tree/dev/Code/Engine/RendererVulkan
It uses [the ShaderCompilerDXC ](https://github.com/ezEngine/ezEngine/tree/dev/Code/Engine/ShaderCompilerDXC) for shader compilation.

You can enable it in the cmake options.

**Comment by TheFloatingBrain** [comment]
Thank you :)
