### ISSUE TITLE
[FEATURE] Use a software rasterizer to improve culling

### ISSUE THREAD

**Issue by jankrassnigg** [ezEngine/ezEngine#621]
See this repo:
https://github.com/rawrunprotected/rasterizer/tree/master/SoftwareRasterizer

It implements a very fast software rasterizer. The idea would be to use this for occlusion culling.

Basically, at the start of a frame, rasterize all occluders. For this one could use the greybox geometry.
Then during the culling phase that currently only uses frustum culling, use the bounding box or sphere of an object to check whether it is occluded and early out.

There are a couple of steps to achieve this:

The rasterizer is currently written as a demo application. It would need to be cleaned up and separated out into a stand-alone library. Probably not difficult though. If one were to attempt this, first contact the author and make sure to submit all changes back to that repository so that others benefit from that work as well.

AFAIK currently the library only rasterizes triangles. There is potential for more performance by rasterizing quads, boxes or spheres directly. Should be discussed with the author. Not important for a first integration though.

The library uses MSVC specific SSE instructions and thus only works on Windows ATM. Again, could be discussed with the author, whether there are ways to also bring this to other platforms. Again, not important, as we can easily disable the optimization where it's not available.

**Comment by nemerle** [comment]
There is also this project here https://github.com/GameTechDev/MaskedOcclusionCulling  might be of some use
