### ISSUE TITLE
Asset browser: Option to expand folder of selected asset

### ISSUE THREAD

**Issue by jankrassnigg** [ezEngine/ezEngine#625]
The asset context menu in the asset browser should have an option to expand the folders in which the asset resides, so that it is easier to find assets next to it. Maybe a "filter to this folder" thing.

**Comment by TheophilusE** [comment]
Can you explain further what you mean by this? Perhaps an example, thanks.

**Comment by jankrassnigg** [comment]
When you select an asset, you do not know in which folder it is located. Often I want to see assets that I know are on disk next to that. So I want the folder filter to be set to the selected assets folder, so that the browser only shows those assets. So when I select "filter to this" I want the folder hierarchy to be expanded and selected to the folder of the selected asset.
