### ISSUE TITLE
Asset browser should show all files on disk and allow import

### ISSUE THREAD

**Issue by jankrassnigg** [ezEngine/ezEngine#626]
The asset browser should have an option to show
* only assets
* all files
* all importable files (?)

If possible, the OS-registered file icon should be used to display non-assets.

The context-menu for non-assets should allow to open them (default program), open their folder in Explorer and, if they are a known file type, import them as an asset.

E.g. for .obj "Import > Mesh with Materials / Mesh without Materials / Animated Mesh ..."

If one selects multiple non-assets of the same type, apply the same import to all of them. For different types, only display the overlapping actions, e.g. can't import .fbx and .png at the same time.

**Comment by na2axl** [comment]
I think that will be nice for the user experience. It will be more complete if the user also has the ability to interact with non-assets files by drag-n-dropping them into component properties with an `ezFileBrowserAttribute` matching the dragged file extension. This will reduce the number of clicks a lot!

**Comment by jankrassnigg** [comment]
Related to #429

**Comment by jankrassnigg** [comment]
Implemented by #1091
