### ISSUE TITLE
Clear editor log on play

### ISSUE THREAD

**Issue by jankrassnigg** [ezEngine/ezEngine#628]
There should be an option to automatically clear the log panel whenever simulate or play-the-game is enabled.

The state needs to be stored in ezEditorPreferencesUser, which means it would be editable in the [preferences](https://ezengine.net/pages/docs/editor/editor-settings.html#preferences). More UI is probably not necessary.

Would then need to listen for play-the-game state change and clear the log. 

See 
* ezGameObjectDocumentEvent
* ezGameObjectDocument::s_GameObjectDocumentEvents
* ezTypeScriptAssetDocumentManager::GameObjectDocumentEventHandler
* ezEditorPreferencesUser

**Comment by ArshErgon** [comment]
okay maybe I could do it, how am I going to run it locally?

**Comment by jankrassnigg** [comment]
Please familiarize yourself with using the engine a bit. You will find information about that here:
http://ezengine.net/#getting-started

**Comment by neilmewada** [comment]
Hi @jankrassnigg! I'll take a look at it. Just got the dev engine build running locally and going through the codebase. Thanks for the info.
P.S. There are 2 types of logs (editor & engine). You only want to clear editor logs, right?
