### ISSUE TITLE
Remove zlib

### ISSUE THREAD

**Issue by jankrassnigg** [ezEngine/ezEngine#638]
EZ has support for compression using zlib (but NOT the .zip format). This has been superseeded by the much superior zstd.

There is really no reason to keep zlib in any longer.

1. Remove Code\ThirdParty\zlib
2. Search CMakeLists.txt and .cmake files for EZ_3RDPARTY_ZLIB_SUPPORT and remove that.
3. Search the code for BUILDSYSTEM_ENABLE_ZLIB_SUPPORT and remove all zlib related code paths.

This should be a trivial task that requires no knowledge of the EZ codebase.

**Comment by ArshErgon** [comment]
Hey @jankrassnigg, I'm on it.

**Comment by ArshErgon** [comment]
hey @jankrassnigg I have a question, regarding the third point, what do you mean by all the code paths? and if I delete anything related to zlib inside those files, I'm pretty sure it will give an error, so do I have to remove the entire file? and there's a file also `CompressedStreamZlib.h` should I remove this also?

**Comment by jankrassnigg** [comment]
Everything that is surrounded with #ifdef BUILDSYSTEM_ENABLE_ZLIB_SUPPORT / #endif can be removed without breaking the code. If that is literally everything in a file (like for CompressedStreamZlib.h and .cpp) then yes, please remove the file. Just rerun CMake afterwards (using GenerateWin64vs2022.bat) and check that it still compiles.
