### ISSUE TITLE
[BUG] Engine won't start

### ISSUE THREAD

**Issue by BlacksmithSouls** [ezEngine/ezEngine#681]
It closes after showing the logo for 2 seconds. I also tried to run all .bat files, but only these ones - Sample - ComputeShaderHistogram, Sample - TextureSample - were launched.

I checked previous releases:
ezEngine Release June 2021 (Patch 1) [Not Started]
ezEngine Release August 2020 [Started]

My PC: GTX 650 1gb, DX12 installed, AMD Athlon(tm) II X4 651 Quad-Core Processor 3.00 GHz, 16GB RAM

**Comment by jankrassnigg** [comment]
Which OS are you on? We only support windows 10 and 11. There should be a log.htm file somewhere in %appdata%, it may contain more info why it crashes. Otherwise, check out the repo, compile in debug and start the editor to see the callstack of the crash.

**Comment by BlacksmithSouls** [comment]
Windows 10 Pro 19044.1889

 log.htm is empty

**Comment by BlacksmithSouls** [comment]
Now the engine starts, but crashes after starting the project

[log 1.txt](https://github.com/ezEngine/ezEngine/files/9540364/log.1.txt)
[log 2.txt](https://github.com/ezEngine/ezEngine/files/9540366/log.2.txt)
[log 3.txt](https://github.com/ezEngine/ezEngine/files/9540367/log.3.txt)

**Comment by jankrassnigg** [comment]
Interesting, seems like an SSE issue. Your CPU might not support one of the instructions that we are using. Not sure how old it is. @C-Core might know better whether it should work.

**Comment by jankrassnigg** [comment]
Also maybe @Ingrater

**Comment by Ingrater** [comment]
@BlacksmithSouls after hitting the crash, could you please open the disassembly view (Menu Debug -> Disassembly) and Post the line the arrow is pointing to and a few lines sourronding that location?

**Comment by BlacksmithSouls** [comment]
00007FF99397A505  mov         rax,qword ptr [position]  
      00007FF99397A50D  movdqu      xmm0,xmmword ptr [rax]  
      00007FF99397A511  movdqu      xmmword ptr [mangled],xmm0  
mangled = mangled.CompMul(BIT_NOISE1);
      00007FF99397A51A  movdqa      xmm0,xmmword ptr [mangled]  
=> 00007FF99397A523  pmulld      xmm0,xmmword ptr [BIT_NOISE1]  
      00007FF99397A52A  movdqa      xmmword ptr [rsp+1B0h],xmm0  
      00007FF99397A533  movdqa      xmm0,xmmword ptr [rsp+1B0h]  
      00007FF99397A53C  movdqa      xmmword ptr [rsp+1A0h],xmm0  
      00007FF99397A545  movdqa      xmm0,xmmword ptr [rsp+1A0h]  
      00007FF99397A54E  movdqa      xmmword ptr [rsp+0F0h],xmm0  
      00007FF99397A557  movaps      xmm0,xmmword ptr [rsp+0F0h]  
      00007FF99397A55F  movdqa      xmmword ptr [mangled],xmm0  
mangled += seed;

**Comment by C-Core** [comment]
Yep it is an SSE issue:
**pmulld** is integer multiplication which is an SSE 4.1 instruction. Your CPU only supports SSE 4a but not SSE 4.1, so that explains the crash.
You could try to change the minimum SSE level in 
Code\Engine\Foundation\SimdMath\Implementation\SSE\SSETypes_inl.h line 11
`#define EZ_SSE_LEVEL EZ_SSE_41`
to
`#define EZ_SSE_LEVEL EZ_SSE_31`
We should have fallback code where ever we use SSE 4.1 instructions but it was never fully tested, so no guarantee that it works.

**Comment by BlacksmithSouls** [comment]
Error while compiling:

[log 1.txt](https://github.com/ezEngine/ezEngine/files/9540696/log.1.txt)
[log 2.txt](https://github.com/ezEngine/ezEngine/files/9540697/log.2.txt)

**Comment by C-Core** [comment]
Well it looks like we're missing a couple of fallbacks. You could disable SSE completely on windows to get the engine running:
Code\Engine\Foundation\Basics\Platform\Win\PlatformFeatures_win.h line 79:
`#  define EZ_SIMD_IMPLEMENTATION EZ_SIMD_IMPLEMENTATION_SSE`
to
`#  define EZ_SIMD_IMPLEMENTATION EZ_SIMD_IMPLEMENTATION_FPU`

**Comment by BlacksmithSouls** [comment]
Okay, now it works. Thank you.
