### ISSUE TITLE
[BUG] Unable to use init/finalize CMake files in game projects

### ISSUE THREAD

**Issue by na2axl** [ezEngine/ezEngine#685]
I think the issue is caused by commit cebf74d906c2abdadb8a84925c1ba1e6231506a3. Since this I am not able to use init.cmake and finalize.cmake files in my game project (under the CppSource directory). It seems that the `ez_init_projects()` and `ez_finalize_projects()` only look in the EZ code. My CMakeLists.txt file:

```cmake
cmake_minimum_required(VERSION 3.21)

project (Inifura VERSION 1.0 LANGUAGES C CXX)

if(PROJECT_IS_TOP_LEVEL)

	set (EZ_SDK_DIR "" CACHE PATH "The ezEngine SDK root directory.")

	# fix output directory
	set (EZ_OUTPUT_DIRECTORY_LIB "${EZ_SDK_DIR}/Output/Lib" CACHE PATH "Where to store the compiled .lib files.")
	set (EZ_OUTPUT_DIRECTORY_DLL "${EZ_SDK_DIR}/Output/Bin" CACHE PATH "Where to store the compiled .dll files.")

	set (CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${EZ_SDK_DIR}/Code/BuildSystem/CMake")

	include("ezUtils")

	ez_include_ezExport()

	ez_configure_external_project()

endif()

ez_init_projects()

# include all projects in the sub-folders
ez_add_all_subdirs()

ez_finalize_projects()
```

**Comment by jankrassnigg** [comment]
@Ingrater this is a similar case to what I mentioned yesterday. Seems it is indeed a problem that we don't glob for some files from the top level anymore.

**Comment by Ingrater** [comment]
@na2axl could you please give this a try https://github.com/ezEngine/ezEngine/pull/686, and see if that fixes your issue?

**Comment by na2axl** [comment]
@Ingrater #686 make it works perfectly 👌🏾
