### ISSUE TITLE
[FEATURE] Triangle collision meshes: option to discard submeshes

### ISSUE THREAD

**Issue by jankrassnigg** [ezEngine/ezEngine#747]
Add checkbox per surface slot to discard this submesh so that fine details (e.g. small branches and leaves of trees) can be ignored, but the rough geometry can be used for the collision mesh.

**Comment by C-Core** [comment]
I don't think it is worth to invest time in a feature like this. It takes less than a minute to delete geometry by material in Blender, plus you have more control over what you actually want in a collision mesh that way. If you create a proper game you will have different mesh files for rendering and collision anyways.
