### ISSUE TITLE
[BUG] Editor performance wont go above 80FPS regardless of scene complexity

### ISSUE THREAD

**Issue by ghost** [ezEngine/ezEngine#823]
**Bug description:**
Regardless of what i am doing within the editor from looking at an empty scene to loading a complex level the editor scene will always be around 80FPS. meanwhile when in player i get around 500-900 fps. To me this points at some kind hard limit in the editor for some reason.

**How to Reproduce:**
1. Launcher editor in any way
2. enable show fps cvar
3. observe fps

**Screenshots:**
![image](https://user-images.githubusercontent.com/120124061/206515102-b82bc4cf-82f6-42a3-8bcb-3df36c4a31fb.png)

**Dev-branch commit hash:**
[24024668197baf79106a58de2cb88fafc0022fc0](https://github.com/ezEngine/ezEngine/tree/24024668197baf79106a58de2cb88fafc0022fc0)

**Comment by jankrassnigg** [comment]
Yes, the editor doesn't render at full speed, so that it doesn't unnecessarily hogs your entire system. For performance measurements use the player.

**Comment by ghost** [comment]
is there a way where this can be changed?
or potentially exposed as a setting

**Comment by jankrassnigg** [comment]
Uh not sure how that's handled atm. It also has to distribute frame rendering for multiple windows, if more than one is visible, so it's not a trivial thing. Imo there isn't much value in rendering at full speed. If you really want that, you would need to dig through the code a bit.

**Comment by ghost** [comment]
ill see what i can find. i was looking to cap to 120 as its more reasonable for my machine

**Comment by ghost** [comment]
looks like its located in ezQtUiServices
would be nice to see this exposed for users to control.

**Comment by ghost** [comment]
final note to avoid spam. VSync looks to work perfectly for capping to a reasonable framerate. I feel running uncapped with vsync or some other optional cap would be a better approach.

**Comment by jankrassnigg** [comment]
Just out of curiosity, did you simply adjust ezQtUiServices::TickEvent::m_fRefreshRate from 60 to something higher? And then enable v-sync?
We could probably expose the target FPS as an editor preference.

**Comment by ghost** [comment]
I set it to 0 for now so that i runs with an unlimited cap. I then use V-Sync for when i need to cap frame rates. My monitor is 144hz and in addition to that uncapped Its just gives much faster iteration time when doing initial performance checks on new rendering features. Deep dives will then be done in standalone.

I did look into doing it in the editor preferences but this looked to exist in the GuiFoundation if i remember correctly and didnt want to mess with passing things around just yet myself

**Comment by jankrassnigg** [comment]
Okay, good to know, I might look into exposing this at some point.
