### ISSUE TITLE
[FEATURE] Component to add a fullscreen effect

### ISSUE THREAD

**Issue by jankrassnigg** [ezEngine/ezEngine#824]
We could use a component that, when present in a scene, renders a fullscreen quad.

It should be configurable at what point it is rendered (pre / post tonemapping etc). Need a way to define the sorting order.
You can select which material to use.
It should expose a color or some other way to input custom parameters.

For maximum flexibility it may also be useful to be able to rotate and offset the quad, so that one can place blotches at different places in screenspace and rotate them around the screen axis. Then one would also need a scale/size value.

This can be used for:
* Full screen pictures (loading screen background)
* Fade in / out masks
* Some HUD elements

**Comment by C-Core** [comment]
I don't think that we need a separate component for this feature. There are a couple of things though we need to add to the regular mesh rendering to make this use case possible. Those additions will be benefitial for other things as well:
1. Expose the render data category on the mesh component (dynamic enum) => defines at what point the mesh is rendered. We might need to add a few categories for screenspace FX.
2. Add a sorting key to the mesh component that can also be used for e.g. transparent meshes to force a certain order.
3. Provide a material/shader template that transforms the mesh in screenspace. Basically a regular fullbright material with a slightly different Vertex Shader. For offset, rotate and scale the regular game object transform can be used but reinterpreted as screenspace. X -> left/right, Y up/down etc.

This has also the benefit that then any mesh can be used for screenspace FX, not only quads.

**Comment by jankrassnigg** [comment]
Sounds like a good solution.
