### ISSUE TITLE
[FEATURE] Local environment volumes + system

### ISSUE THREAD

**Issue by jankrassnigg** [ezEngine/ezEngine#832]
Allow to place volumes in a scene that classify what type of area it is (or what local parameters exist there.

This volume can be sampled (using a location) to return various parameters (maybe as a blackboard). Each volume would just select an area type ("default", "water", "smoke", "room", "forest", ...). Each area preset has a bunch of parameter values associated. Potentially these presets would be resources / assets, and if so, we probably would want to use a hierarchy, so that you can have a base environment which defines the generally available values, and the derived environments override the specifics.

The values would be something like tonemapping parameters, sound parameters, but also AI related (visibility), or gameplay (underwater, area damage, ...).

Every system can then query the parameter set, e.g. at the location of the camera, and then change its behvaior (post processors, sound effects).

Volumes would need a "fuzzy edge" for things like fog or room ambience to fade in/out smoothly, but for volumes like water the fuzziness would be zero.

**Comment by jankrassnigg** [comment]
@C-Core is this fully completed, or are we still missing something ?

**Comment by C-Core** [comment]
It's complete so far
