### ISSUE TITLE
[BUG] Windows MSVC(vs 2022) Static Linking Fails to build.

### ISSUE THREAD

**Issue by JailbreakPapa** [ezEngine/ezEngine#839]
**Bug description:**

**How to Reproduce:**
A clear description what steps to take to reproduce the issue.
1. Configure Ez with cmake cmd/gui with the option: EZ_COMPILE_ENGINE_AS_DLL set to off.
2. Generate, and open the sln and build.
 3. These Projects Should Give LNK Errors: ezEditorFramework, ezXboxControllerPlugin, ezInspector

**Dev-branch commit hash:**
4eec40f803026f9eca68723391ab8866dcf791c9

**Comment by jankrassnigg** [comment]
I guess you mean EZ_COMPILE_ENGINE_AS_DLL set to OFF ?

**Comment by JailbreakPapa** [comment]
> I guess you mean EZ_COMPILE_ENGINE_AS_DLL set to OFF ?

oh yea, looks like I didn't check that, ill change it right now(the perks of writing issues when your tired...)
