### ISSUE TITLE
[FEATURE] Add 2D Objects for create platformers

### ISSUE THREAD

**Issue by Geniok** [ezEngine/ezEngine#858]
**Is your feature request related to a problem? Please describe:**
To be able to create a 2D platformer, you need to have the right elements. Such as Tilemap, Colliders 2D, Texture Editor.

**Describe the solution you'd like:**
Add 2D graphics.

**Additional context:**
More details can be found here: https://gamedevacademy.org/how-to-build-a-complete-2d-platformer-in-unity/

**Comment by jankrassnigg** [comment]
For the foreseeable future I would say this is out of scope for us. 2D is a rather broad topic, you would also need a proper 2D physics engine (Box2D) integration and various tools. Most of this has no use for 3D use cases.

If anyone is interested in working on 2D stuff, feel free to contact me, but the core dev team is probably not going to work on this any time soon.

**Comment by Geniok** [comment]
Thanks for the answer!
I will try to implement something.

The question arose, can I now use texture atlases?

How is texture tiling calculated now? Is it possible to specify the number of repetitions?

**Comment by jankrassnigg** [comment]
There is no built-in support for texture atlases. We only support single textures:
https://ezengine.net/pages/docs/graphics/textures-overview.html

You can generate your atlas outside of ez and reference it as a normal texture. If you want more control, you would need to build a texture atlas asset and all the infrastructure around how to use that somehow. That's not a small task.
