### ISSUE TITLE
[BUG] Potential overwrite concern with code in DocumentManager.cpp line 420.

### ISSUE THREAD

**Issue by antonyjones67** [ezEngine/ezEngine#888]
Hash: 312412

Howdy, 
I noticed a potential overwrite in DocumentManager.cpp line 420.

419 pDocument->BeforeClosing();
420 delete pDocument;                                     <- I noticed that pDocument is getting deleted.

422 e.m_pDocument = pDocument;                 <- Before it gets used. This looked suspicious.
423 e.m_Type = Event::Type::DocumentClosed;
424 s_Events.Broadcast(e);

Am I reading this wrong?

**Comment by jankrassnigg** [comment]
It looks suspicious yes, but it is correct. I'll add a comment to make it clearer.
