### ISSUE TITLE
Restart Engine View Process

### ISSUE THREAD

**Issue by dogpacolypse100** [ezEngine/ezEngine#916]
I couldn't wait to install this until I've ran into a problem with the viewport with text describing "Restart Engine View Process" and I would like to know if this is normal or not, Please help.

**Comment by jankrassnigg** [comment]
I don't understand what you mean, please describe your problem properly.

**Comment by windyslove** [comment]
![2023-11-25_16-12-44](https://github.com/ezEngine/ezEngine/assets/6903175/0c7049c8-d97d-4d67-bbb9-a17599b1d551)
我编译完也不能运行，也显示的这样子

**Comment by jankrassnigg** [comment]
Is this on Linux? Linux isn't fully working yet.

**Comment by dogpacolypse100** [comment]
> Is this on Linux? Linux isn't fully working yet.

My problem is on windows, I think it could be a problem with building the software but I'm not completely sure.

**Comment by Sanakan8472** [comment]
@dogpacolypse100 can you switch to the Log tab and look at the engine process log? It should print why it crashed:
![image](https://github.com/ezEngine/ezEngine/assets/11784812/c3283eb7-29f1-4c9e-934a-25c82fa46eb0)
