### ISSUE TITLE
After importing an Animated Mesh and Skeleton as FBX from Mixamo and assigning a Skeleton to the Animated Mesh, I was unable to see the Mesh in the editor. 

### ISSUE THREAD

**Issue by antonyjones67** [ezEngine/ezEngine#930]
After importing an Animated Mesh and Skeleton as FBX from Mixamo and assigning a Skeleton to the Animated Mesh and transforming the Animated Mesh asset, I was unable to see the Mesh in the editor.
If I restart the editor the Mesh shows up just fine. I am not sure why the mesh is not updated after being transformed.

Commit hash.
fb2679e780435a28192bbc390adba82971a64a87
"Prefabs may now attach components to their parent instance node (#927)"

**Comment by jankrassnigg** [comment]
Duplicate of #631.

**Comment by antonyjones67** [comment]
Cool. Thank you.
