### ISSUE TITLE
Pacman does not move after clicking arrows in Shipping build.

### ISSUE THREAD

**Issue by antonyjones67** [ezEngine/ezEngine#932]
Notice that in Debug and Dev builds, PacMan moves when using the arrow keys. In a Shipping build, arrow keys do not move Pacman. I have found what might be a similar issue come up that I was able to debug. It looked like input messages being sent are not being reached in some cases in a Shipping build.

I am currently on this build. Hash Commit. fb2679e780435a28192bbc390adba82971a64a87

You can reproduce by Exporting PacMan. Then launching Pacman from the batch file.

Thank you.

**Comment by jankrassnigg** [comment]
I tried the Shipping build and it worked for me. So it doesn't seem to be related to the Shipping configuration itself, but there are other potential issues.

First, are you sure that the PacMan plugin was compiled successfully? This is done automatically when you export the scene:

![grafik](https://github.com/ezEngine/ezEngine/assets/6001174/e2a442e9-d0dc-4185-a13f-7939781b75f7)

But it is currently NOT done automatically when you just use the Play-the-Game mode. To do that, use this menu item:

![grafik](https://github.com/ezEngine/ezEngine/assets/6001174/3eac49ca-83aa-4d2b-9683-0345dc6ba043)

Finally, there is also this problem: https://github.com/ezEngine/ezEngine/issues/817

I still don't know when and why this happens, but sometimes the editor removes the reference to the game plugin from it's settings. Then when you launch the game, it simply doesn't load the plugin, and therefore no code is being executed, which usually means that you can't do anything. Though in this case the ghosts should then also not do anything.

If that was the case, you should see in git, that a config file was modified, and you can revert that.

Finally, while looking at the sample I also noticed this: https://github.com/ezEngine/ezEngine/issues/937
That's probably a regression from https://github.com/ezEngine/ezEngine/pull/927 (sigh).

**Comment by jankrassnigg** [comment]
Another problem I noticed, is that the CMake project generation is specific to the build type, e.g. it is either for Debug, Dev or Shipping. If you switch between those builds, you need to re-run "Setup C++ Plugin..." and overwrite the solution, to get the correct build, otherwise "Compile Plugin" won't work.

Unfortunately there are still a lot of kinks to iron out over time.

**Comment by jankrassnigg** [comment]
@antonyjones67 I've fixed several bugs and added a couple of improvements that should make it much easier to have the C++ code up to date. I think those should prevent such issues in the future. I'll close the ticket for now. Feel free to re-open or open a new ticket, if you still encounter such problems.

**Comment by antonyjones67** [comment]
It looks like you fixed the issue Pacman. Thank you! :)
