### ISSUE TITLE
Imported an FBX with animation and the Animation Clip duration is incorrect. So the Animated Mesh plays the animation too quickly.

### ISSUE THREAD

**Issue by antonyjones67** [ezEngine/ezEngine#934]
I believe the problem is with AssimpAnimationImport.cpp line 86/87. 
This fixed the issue.

      //const double fOneDivTicksPerSec = 1.0 / 1000.0; <- bug
      const double fOneDivTicksPerSec = 1.0f / pAnim->mTicksPerSecond; <- fixes issue
      
Thank you.

**Comment by jankrassnigg** [comment]
This is a recurring bug in assimp where it's sometimes broken for some assets, then somebody changes the code, then it's broken for other assets.
Maybe we need to expose an option to override this on our side, ie have a checkbox in the asset to fix this when the automatic detection fails. Not sure.

**Comment by TheophilusE** [comment]
I have already mentioned this to Jan, the most viable method which I implemented was to expose the animation frame rate to be used instead. Since in reality, that may be needed in many other occasions.

**Comment by jankrassnigg** [comment]
As always, if anyone has a decent fix, I'm happy to accept a pull request.

**Comment by antonyjones67** [comment]
Thank you, @jankrassnigg
!
