### ISSUE TITLE
[FEATURE] Investigate making it possible to integrate other profilers

### ISSUE THREAD

**Issue by jankrassnigg** [ezEngine/ezEngine#941]
It might be useful if people can more easily add support for other profiling tools than just the JSON based Chrome tracing functionality.

A useful one might be Optick:
https://github.com/bombomby/optick

From a discussion:

First create an init.cmake file in the Thirdparty/Optick directory

```
# #####################################
# ## Optick Profiler support
# #####################################

set (EZ_BUILD_OPTICK ON CACHE BOOL "Whether support for the Optick profiler should be added")

# #####################################
# ## ez_requires_optick()
# #####################################

macro(ez_requires_optick)
  ez_requires(EZ_BUILD_OPTICK)
endmacro()
```

Add the Optick sources to this directory here is an example cmake build script

```
ez_cmake_init()

ez_requires_optick()

# Get the name of this folder as the project name
get_filename_component(PROJECT_NAME ${CMAKE_CURRENT_SOURCE_DIR} NAME_WE)

ez_create_target(SHARED_LIBRARY ${PROJECT_NAME} NO_EZ_PREFIX)

set_target_properties(${PROJECT_NAME}
    PROPERTIES 
        PUBLIC_HEADER "${CMAKE_CURRENT_LIST_DIR}/optick.h;${CMAKE_CURRENT_LIST_DIR}/optick.config.h"
)

target_compile_definitions(${PROJECT_NAME} PRIVATE OPTICK_EXPORTS=1)

target_compile_definitions(${PROJECT_NAME} PUBLIC
  USE_OPTICK=1
  OPTICK_USE_VULKAN=0
  OPTICK_USE_D3D12=0
  OPTICK_BUILD_GUI_APP=0
  OPTICK_ENABLE_GPU_VULKAN=0
  OPTICK_ENABLE_GPU_D3D12=0
)

if(MSVC)
  # temporary solution to unblock C++17 users
  target_compile_definitions(${PROJECT_NAME} PRIVATE _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS)
endif()
```

In the Foundation/Profiling/Profiling.h header, implement the following

```
#ifdef USE_OPTICK
#  include <Optick/optick.h>

/// CPU Profiling

/// \brief Basic scoped performance counter. Use this counter 99% of the time. It automatically extracts the name
/// of the current function. Users can also pass an optional name for this macro to override the name
/// - EZ_OPTICK_PROFILE_EVENT("szScopeName");. Useful for marking multiple scopes within one function.
#  define EZ_OPTICK_PROFILE_EVENT(...) OPTICK_EVENT(__VA_ARGS__)
#else
#  define EZ_OPTICK_PROFILE_EVENT(...)
#endif

...

// Add the Optick profile event to the existing profile macro.
#  define EZ_PROFILE_SCOPE(szScopeName)                                                                             \
    ezProfilingScope EZ_CONCAT(_ezProfilingScope, EZ_SOURCE_LINE)(szScopeName, EZ_SOURCE_FUNCTION, ezTime::Zero()); \
    EZ_OPTICK_PROFILE_EVENT(szScopeName)
```

In the main application loop Foundation/Application/Implementation/MainLoop.cpp, implement something of the following;

```
// Include the profiling header
#include <Foundation/Profiling/Profiling.h>

// You may modify the main loop function to behave like the following
void ezRun_MainLoop(ezApplication* pApplicationInstance)
{
#ifdef USE_OPTICK
  while (true)
  {
    OPTICK_FRAME("MainThread");

    ezApplication::Execution pResult = pApplicationInstance->Run();
    if (pResult == ezApplication::ezApplication::Execution::Quit)
    {
      break;
    }
  }
#else
  while (pApplicationInstance->Run() == ezApplication::Execution::Continue)
  {
  }
#endif
}

// Ensure to shut down the optick profiler
void ezRun_Shutdown(ezApplication* pApplicationInstance)
{
  ...

#ifdef USE_OPTICK

  // Release Optick Profiler Internal Memory
  OPTICK_SHUTDOWN();

#endif // USE_OPTICK
}
```

It would be nice, if a custom profiler could be integrated without modifying the EZ code, e.g. maybe we could provide a few callbacks that can be set instead. That way Optick could be provided as an EnginePlugin instead, that can be enabled from the editor when desired.

**Comment by C-Core** [comment]
A profiler is such an integral part of the engine that I don't think it makes sense to add them via an EnginePlugin. E.g. using callbacks would have a significant performance overhead. I would go for defines and cmake variables.

**Comment by TheophilusE** [comment]
I do agree. However, with Tracy, I have noticed that it infiltrates the codebase in undesirable ways, from loading its dependent libraries (some symbols are already initialized before the stack walker), to masking compiler warnings and breaking compilation in rare cases. I understand it is quite an advance library though, so that offsets that. I assume may be ways to fix those with the library itself that I did not try.

**Comment by jankrassnigg** [comment]
A define / CMake option is fine with me. Either way, it would be nice, if it were generic enough, e.g. if I can just switch an option in CMake and somehow it injects custom code in the right places to make use of a custom library. Not sure exactly how to do that, though.

**Comment by TheophilusE** [comment]
Which third party profiler are you all interested in? (preferably free and open source)

**Comment by jankrassnigg** [comment]
We have Tracy now, additionally to the EZ system. This should be enough.
