### ISSUE TITLE
Please support MSYS2 MINGW64

### ISSUE THREAD

**Issue by ghost** [ezEngine/ezEngine#992]

**Comment by Ingrater** [comment]
We currently support the Microsoft Visual C++ compiler (msvc) and clang when targeting windows. Both compilers are freely available at no cost. We currently do not plan on supporting MingGW when targeting windows, we do hover support gcc when targeting linux. Supporting MinGW is significant effort as it can not link against libaries / object files produced by the microsoft toolchain. This means all our third party dependencies need to be compiled with MinGW and provided in addition to the ones we already provide for msvc / clang. Given this significant required effort there is just not enough benefit to supporting MinGW.

For more information on how to build on windows see: https://ezengine.net/pages/docs/build/build-windows.html
and https://ezengine.net/pages/docs/build/clang-on-windows.html

Pull requests for additional compiler support are always welcome though.
